import { createClient } from "npm:@supabase/supabase-js@2";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

interface Recipient {
  phone: string;
  name?: string;
  email?: string;
  city?: string;
  state?: string;
  document?: string;
  notes?: string;
}

const variableFieldMap: Record<string, string> = {
  'contact_name': 'name',
  'contact_full_name': 'name',
  'contact_phone': 'phone',
  'contact_email': 'email',
  'contact_city': 'city',
  'contact_state': 'state',
  'contact_document': 'document',
  'contact_notes': 'notes',
};

// Campaign sends must always reach a terminal state.
// External provider failures are marked as failed immediately so the campaign can finish.
const RETRYABLE_ERRORS: Record<string, { maxRetries: number; delayHours: number[] }> = {};

// No Meta business error should bounce back to pending automatically.
// This was causing looping recipients and unstable counters.
const THROTTLE_ERRORS: string[] = [];

const PERMANENT_ERRORS = [
  '131026', '131042', '131021', '131047', '132001', '132000', '100', '135000',
];

function getFirstName(fullName: string | undefined): string {
  if (!fullName) return '';
  return fullName.split(' ')[0];
}

function isAutoGeneratedLeadName(name?: string | null): boolean {
  return !name || name.startsWith('LeadWhats-') || name.startsWith('WhatsApp ');
}

function getPhoneLookupKeys(phone: string): string[] {
  const digits = phone.replace(/\D/g, '');
  if (!digits) return [];

  const withoutCountryCode = digits.startsWith('55') ? digits.slice(2) : digits;

  return [...new Set([
    digits,
    withoutCountryCode,
    withoutCountryCode.slice(-9),
    withoutCountryCode.slice(-8),
  ].filter(Boolean))];
}

function setPreferredName(map: Map<string, string>, key: string, name?: string | null) {
  if (!key || !name) return;

  const current = map.get(key);
  if (!current || (isAutoGeneratedLeadName(current) && !isAutoGeneratedLeadName(name))) {
    map.set(key, name);
  }
}

const VALID_BRAZILIAN_DDDS = [
  '11', '12', '13', '14', '15', '16', '17', '18', '19',
  '21', '22', '24', '27', '28',
  '31', '32', '33', '34', '35', '37', '38',
  '41', '42', '43', '44', '45', '46',
  '47', '48', '49',
  '51', '53', '54', '55',
  '61', '62', '64', '63', '65', '66', '67',
  '71', '73', '74', '75', '77', '79',
  '81', '87', '82', '83', '84', '85', '88', '86', '89',
  '91', '93', '94', '92', '97', '95', '96', '98', '99',
  '68', '69',
];

function formatPhoneNumber(phone: string): string {
  let cleaned = phone.replace(/\D/g, '');
  if (cleaned.startsWith('0')) cleaned = cleaned.substring(1);
  
  let hasCountryCode = false;
  if (cleaned.startsWith('55') && cleaned.length >= 12) {
    hasCountryCode = true;
    cleaned = cleaned.substring(2);
  }
  
  if (cleaned.length === 10) {
    const ddd = cleaned.slice(0, 2);
    const firstDigit = cleaned[2];
    if (VALID_BRAZILIAN_DDDS.includes(ddd) && ['6', '7', '8', '9'].includes(firstDigit)) {
      cleaned = ddd + '9' + cleaned.slice(2);
    }
  }
  
  if (!cleaned.startsWith('55')) cleaned = '55' + cleaned;
  return cleaned;
}

function extractMetaErrorCode(errorMessage: string): string | null {
  const match = errorMessage?.match(/(\d{6})/);
  return match ? match[1] : null;
}

function isRetryableError(errorCode: string | null): boolean {
  if (!errorCode) return false;
  return (!!RETRYABLE_ERRORS[errorCode] || THROTTLE_ERRORS.includes(errorCode)) && !PERMANENT_ERRORS.includes(errorCode);
}

function isThrottleError(errorCode: string | null): boolean {
  return !!errorCode && THROTTLE_ERRORS.includes(errorCode);
}

function getRetryConfig(errorCode: string): { maxRetries: number; delayHours: number[] } | null {
  return RETRYABLE_ERRORS[errorCode] || null;
}

function calculateNextRetryTime(errorCode: string, retryCount: number): Date | null {
  const config = getRetryConfig(errorCode);
  if (!config) return null;
  if (retryCount >= config.maxRetries) return null;
  const delayHours = config.delayHours[retryCount] || config.delayHours[config.delayHours.length - 1];
  return new Date(Date.now() + delayHours * 3600 * 1000);
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
  const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
  const supabase = createClient(supabaseUrl, supabaseServiceKey);

  // External DB SSoT for conversation_assignments (with internal fallback)
  const _extUrl = Deno.env.get('EXTERNAL_SUPABASE_URL');
  const _extKey = Deno.env.get('EXTERNAL_SUPABASE_SERVICE_ROLE_KEY');
  const externalSupabase = (_extUrl && _extKey) ? createClient(_extUrl, _extKey) : null;
  const caDb = externalSupabase;

  // meta-send runs on the internal Supabase (Lovable Cloud)
  const metaSendUrl = supabaseUrl;
  const metaSendKey = supabaseServiceKey;

  try {
    const { campaignId, batchSize = 1, processRetries = false } = await req.json();

    if (!campaignId) {
      return new Response(
        JSON.stringify({ error: 'Campaign ID required' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Load campaign
    const { data: campaign, error: campaignError } = await supabase
      .from('campaigns')
      .select('*, campaign_channels(channel_id, template_id, order_index)')
      .eq('id', campaignId)
      .single();

    if (campaignError || !campaign) {
      return new Response(
        JSON.stringify({ error: 'Campaign not found' }),
        { status: 404, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Check status
    if (campaign.status !== 'running' && !(processRetries && campaign.status === 'completed')) {
      const { count: pendingRetries } = await supabase
        .from('campaign_recipients')
        .select('*', { count: 'exact', head: true })
        .eq('campaign_id', campaignId)
        .eq('status', 'waiting_retry')
        .lte('next_retry_at', new Date().toISOString());
      
      if (pendingRetries && pendingRetries > 0) {
        console.log(`[Batch] Campaign ${campaign.name} has ${pendingRetries} retries ready`);
      } else {
        return new Response(
          JSON.stringify({ success: true, status: campaign.status, done: true, message: `Campaign is ${campaign.status}`, pendingRetries: 0 }),
          { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
      }
    }

    // Get channels and templates
    const campaignChannels = campaign.campaign_channels || [];
    if (campaignChannels.length === 0) {
      await supabase
        .from('campaigns')
        .update({ status: 'failed' })
        .eq('id', campaignId)
        .in('status', ['running', 'scheduled', 'draft']);
      return new Response(
        JSON.stringify({ error: 'No channels configured', done: true }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const nowIso = () => new Date().toISOString();

    async function getCounts() {
      const { data } = await supabase.rpc('get_campaign_counts', { p_campaign_id: campaignId });
      return data?.[0] || { total_sent: 0, total_delivered: 0, total_failed: 0, total_pending: 0, total_waiting_retry: 0, total_processing: 0 };
    }

    async function getRecipientTotal() {
      const { count, error } = await supabase
        .from('campaign_recipients')
        .select('id', { count: 'exact', head: true })
        .eq('campaign_id', campaignId);

      if (error) {
        console.error('[Batch] Error counting campaign recipients:', error);
      }

      return Number(count) || 0;
    }

    async function persistCampaignState(
      counts: { total_sent?: number; total_delivered?: number; total_failed?: number; total_waiting_retry?: number },
      status: 'running' | 'completed',
      totalRecipientsOverride?: number
    ) {
      // CRITICAL: only overwrite status when the campaign is still in a state
      // where the batch is authoritative. If the user paused, cancelled or
      // deleted the campaign meanwhile, NEVER resurrect it back to running.
      const payload: Record<string, unknown> = {
        status,
        sent_count: Number(counts.total_sent) || 0,
        delivered_count: Number(counts.total_delivered) || 0,
        failed_count: Number(counts.total_failed) || 0,
        completed_at: status === 'completed' ? nowIso() : null,
        updated_at: nowIso()
      };

      if (typeof totalRecipientsOverride === 'number' && totalRecipientsOverride > 0) {
        payload.total_recipients = totalRecipientsOverride;
      }

      await supabase.from('campaigns').update(payload).eq('id', campaignId).in('status', ['running', 'completed']);
    }

    async function failOpenRecipientsAndComplete(reason: string, errorCode: string) {
      const { data: updatedRecipients, error: failOpenError } = await supabase
        .from('campaign_recipients')
        .update({
          status: 'failed',
          error_message: reason,
          last_error_code: errorCode,
          next_retry_at: null,
          updated_at: nowIso()
        })
        .eq('campaign_id', campaignId)
        .in('status', ['pending', 'processing', 'waiting_retry'])
        .select('id');

      if (failOpenError) {
        console.error('[Batch] Error failing open recipients:', failOpenError);
      }

      const counts = await getCounts();
      await persistCampaignState(counts, 'completed');

      return new Response(
        JSON.stringify({
          success: true,
          fallback: true,
          done: true,
          status: 'completed',
          error: reason,
          failedOpenRecipients: updatedRecipients?.length || 0,
          sent: Number(counts.total_sent) || 0,
          delivered: Number(counts.total_delivered) || 0,
          failed: Number(counts.total_failed) || 0,
          total: (campaign as { total_recipients: number }).total_recipients,
          pendingRetries: Number(counts.total_waiting_retry) || 0
        }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const channelIds = [...new Set(campaignChannels.map((cc: { channel_id: string }) => cc.channel_id))];
    const templateIds = [...new Set(campaignChannels.map((cc: { template_id: string }) => cc.template_id))];

    const { data: channels } = await supabase.from('channels').select('*').in('id', channelIds);
    const { data: templates } = await supabase.from('message_templates').select('*').in('id', templateIds);

    if (!channels || channels.length === 0 || !templates || templates.length === 0) {
      return await failOpenRecipientsAndComplete('Canais ou templates da campanha não estão mais disponíveis.', 'CONFIG_MISSING');
    }

    // IMPORTANT: avoid blocking dispatch only because `connected` flag is stale.
    // If channel has credentials, we can still attempt sending.
    const dispatchableChannels = channels.filter(c => !!c.access_token);
    if (dispatchableChannels.length === 0) {
      return await failOpenRecipientsAndComplete('Nenhum canal da campanha possui credenciais válidas para envio.', 'CHANNEL_UNAVAILABLE');
    }

    const dispatchableChannelIds = new Set(dispatchableChannels.map(c => c.id));
    const activeCampaignChannels = campaignChannels.filter((cc: { channel_id: string; template_id: string }) =>
      dispatchableChannelIds.has(cc.channel_id)
    );

    if (activeCampaignChannels.length === 0) {
      return await failOpenRecipientsAndComplete('Nenhum dos canais vinculados à campanha está disponível para envio.', 'CHANNEL_REMOVED');
    }

    // Auto-subscribe webhooks on first batch
    if (campaign.sent_count === 0) {
      for (const ch of dispatchableChannels) {
        if (ch.provider === 'meta' && ch.access_token) {
          fetch(`${supabaseUrl}/functions/v1/meta-subscribe-webhook`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${supabaseServiceKey}` },
            body: JSON.stringify({ phoneNumberId: ch.app_name, accessToken: ch.access_token, wabaId: ch.waba_id }),
          }).catch(err => console.error(`[Batch] Webhook subscribe error:`, err));
        }
      }
    }

    const channelsMap = new Map(dispatchableChannels.map(c => [c.id, c]));
    const templatesMap = new Map(templates.map(t => [t.id, t]));
    const isFullMode = campaign.min_interval === 0 && campaign.max_interval === 0;
    const standardTickSize = Math.max(activeCampaignChannels.length, 1);
    // FULL mode: cap parallel calls per tick at 25 to stay under the edge-runtime
    // per-trace rate limit (~100/min). Higher values caused mass "RateLimitError"
    // failures (Retry after 60s) when sending 99 meta-send calls in parallel.
    const effectiveBatchSize = isFullMode
      ? Math.min(Math.max(Number(batchSize) || 25, 1), 25)
      : standardTickSize;
    const recoverableFailedCodes: string[] = [];

    const releaseStaleProcessingRecipients = async () => {
      const staleBefore = new Date(Date.now() - 3 * 60 * 1000).toISOString();

      const { data, error } = await supabase
        .from('campaign_recipients')
        .update({
          status: 'pending',
          next_retry_at: null,
          error_message: null,
          last_error_code: null,
          updated_at: nowIso()
        })
        .eq('campaign_id', campaignId)
        .eq('status', 'processing')
        .lt('updated_at', staleBefore)
        .select('id');

      if (error) {
        console.error('[Batch] Error releasing stale processing recipients:', error);
        return 0;
      }

      const releasedCount = data?.length || 0;
      if (releasedCount > 0) {
        console.warn(`[Batch] Released ${releasedCount} stale processing recipient(s) for campaign ${campaign.name}`);
      }

      return releasedCount;
    };


    const recoverFailedRecipients = async () => {
      if (recoverableFailedCodes.length === 0) {
        return 0;
      }

      const { count, error: recoverableError } = await supabase
        .from('campaign_recipients')
        .select('id', { count: 'exact', head: true })
        .eq('campaign_id', campaignId)
        .eq('status', 'failed')
        .in('last_error_code', recoverableFailedCodes);

      if (recoverableError) {
        console.error('[Batch] Error checking recoverable failed recipients:', recoverableError);
        return 0;
      }

      if (!count) {
        return 0;
      }

      const { error: requeueError } = await supabase
        .from('campaign_recipients')
        .update({
          status: 'pending',
          sent_at: null,
          delivered_at: null,
          read_at: null,
          retry_count: 0,
          error_message: null,
          last_error_code: null,
          next_retry_at: null,
          updated_at: nowIso()
        })
        .eq('campaign_id', campaignId)
        .eq('status', 'failed')
        .in('last_error_code', recoverableFailedCodes);

      if (requeueError) {
        console.error('[Batch] Error requeueing recoverable failed recipients:', requeueError);
        return 0;
      }

      console.log(`[Batch] Requeued ${count} recoverable failed recipients for campaign ${campaign.name}`);
      return count;
    };

    console.log(`[Batch] Campaign ${campaign.name} using tick size ${effectiveBatchSize} (${isFullMode ? 'FULL MODE' : `${standardTickSize} selected channel(s)`})`);
    await releaseStaleProcessingRecipients();

    // ===== ATOMIC CLAIM: Use DB function to prevent race conditions =====
    // This atomically marks recipients as 'processing' so concurrent calls can't grab the same ones
    const { data: claimedRecipients, error: claimError } = await supabase
      .rpc('claim_campaign_recipients', {
        p_campaign_id: campaignId,
        p_batch_size: effectiveBatchSize,
        p_include_retries: true
      });

    if (claimError) {
      console.error('[Batch] Error claiming recipients:', claimError);
      const rawMsg = String(claimError.message || '');
      // Detecta erros transitórios da infra (Cloudflare 5xx, timeouts, gateway) e responde com retry
      const isTransient = /520|521|522|523|524|503|502|504|gateway|timeout|fetch failed|network|unknown error/i.test(rawMsg);
      if (isTransient) {
        console.warn('[Batch] Transient upstream error while claiming - returning retry signal');
        return new Response(
          JSON.stringify({
            success: false,
            transient: true,
            retry: true,
            status: 'running',
            done: false,
            error: 'UPSTREAM_UNAVAILABLE',
            details: 'Upstream temporariamente indisponível ao reservar destinatários. Nova tentativa será feita automaticamente.'
          }),
          { status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
      }
      return new Response(
        JSON.stringify({ error: 'Failed to claim recipients', details: rawMsg }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const recipientsToSend = (claimedRecipients || []).map((r: any) => ({
      phone: r.phone,
      name: r.name || undefined,
      recipientId: r.id,
      isRetry: r.is_retry,
      retryCount: r.retry_count || 0,
      leadId: r.lead_id || undefined
    }));

    console.log(`[Batch] Claimed ${recipientsToSend.length} recipients for campaign ${campaign.name}`);

    // NO LEGACY FALLBACK - only send to campaign_recipients that were atomically claimed
    // This prevents sending to people not in the selected base

    if (recipientsToSend.length === 0) {
      const recoveredFailed = await recoverFailedRecipients();
      if (recoveredFailed > 0) {
        const recoveredCounts = await getCounts();
        await persistCampaignState(recoveredCounts, 'running');

        return new Response(
          JSON.stringify({
            success: true,
            done: false,
            status: 'running',
            sent: Number(recoveredCounts.total_sent) || 0,
            delivered: Number(recoveredCounts.total_delivered) || 0,
            failed: Number(recoveredCounts.total_failed) || 0,
            total: campaign.total_recipients,
            recoveredFailed,
            pendingRetries: Number(recoveredCounts.total_waiting_retry) || 0
          }),
          { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
      }

      const c = await getCounts();
      const actualRecipientTotal = await getRecipientTotal();
      const hasFutureRetries = (Number(c.total_waiting_retry) || 0) > 0;
      const hasPending = (Number(c.total_pending) || 0) > 0;
      const hasProcessing = (Number(c.total_processing) || 0) > 0;
      const totalTerminal = (Number(c.total_sent) || 0) + (Number(c.total_failed) || 0);
      const completionTarget = actualRecipientTotal || campaign.total_recipients;
      const isComplete = !hasPending && !hasProcessing && !hasFutureRetries && totalTerminal >= completionTarget;

      const newStatus = isComplete ? 'completed' : 'running';
      await persistCampaignState(c, newStatus, actualRecipientTotal || undefined);

      return new Response(
        JSON.stringify({
          success: true,
          done: isComplete,
          status: isComplete ? 'completed' : (hasFutureRetries && !hasPending ? 'waiting_retry' : 'running'),
          sent: Number(c.total_sent) || 0,
          delivered: Number(c.total_delivered) || 0,
          failed: Number(c.total_failed) || 0,
          total: actualRecipientTotal || campaign.total_recipients,
          pendingRetries: Number(c.total_waiting_retry) || 0
        }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    let sentThisBatch = 0;
    let failedThisBatch = 0;
    let scheduledRetryThisBatch = 0;

    const manualVariables = campaign.manual_variables as Record<string, string> | null;

    // Pre-fetch custom fields for leads if any template uses custom_field mappings
    const needsCustomFields = templates.some((t: any) => {
      const mappings = t.variable_mappings as Record<string, string> | null;
      return mappings && Object.values(mappings).some((m: string) => m?.startsWith('custom_field:'));
    });

    const leadCustomFieldsMap = new Map<string, Record<string, any>>();
    const leadCustomFieldsByPhoneKey = new Map<string, Record<string, any>>();
    const leadNameById = new Map<string, string>();
    const leadNameByPhoneKey = new Map<string, string>();
    const recipientLeadIds = [...new Set(recipientsToSend.map((r: typeof recipientsToSend[number]) => r.leadId).filter(Boolean))] as string[];
    const recipientPhones = [...new Set(recipientsToSend.map((r: typeof recipientsToSend[number]) => formatPhoneNumber(r.phone)))];

    const [leadsByIdResult, leadsByPhoneResult] = await Promise.all([
      recipientLeadIds.length > 0
        ? supabase.from('leads').select('id, phone, name, custom_fields').in('id', recipientLeadIds)
        : Promise.resolve({ data: [], error: null }),
      (needsCustomFields || recipientPhones.length > 0)
        ? supabase.from('leads').select('id, phone, name, custom_fields').in('phone', recipientPhones)
        : Promise.resolve({ data: [], error: null }),
    ]);

    const leadRecords = [
      ...(leadsByIdResult.data || []),
      ...(leadsByPhoneResult.data || []),
    ];

    for (const lead of leadRecords) {
      if (lead.custom_fields) {
        leadCustomFieldsMap.set(lead.id, lead.custom_fields as Record<string, any>);
        // Also map by phone keys so recipients without lead_id can resolve custom fields
        getPhoneLookupKeys(lead.phone).forEach((key) => {
          if (!leadCustomFieldsByPhoneKey.has(key)) {
            leadCustomFieldsByPhoneKey.set(key, lead.custom_fields as Record<string, any>);
          }
        });
      }

      if (lead.name) {
        setPreferredName(leadNameById, lead.id, lead.name);
        getPhoneLookupKeys(lead.phone).forEach((key) => setPreferredName(leadNameByPhoneKey, key, lead.name));
      }
    }

    async function processRecipient(recipient: typeof recipientsToSend[0], idx: number) {
      const campaignChannel = activeCampaignChannels[idx % activeCampaignChannels.length] as { channel_id: string; template_id: string };
      const channel = channelsMap.get(campaignChannel.channel_id);
      const template = templatesMap.get(campaignChannel.template_id) as {
        id: string; name: string; variables?: string[] | null; variable_mappings?: Record<string, string> | null
      } | undefined;

      if (!channel || !template) {
        await supabase.from('campaign_recipients').update({
          status: 'failed', error_message: 'Canal ou template não encontrado', last_error_code: 'CONFIG_ERROR',
          channel_id: campaignChannel?.channel_id || null
        }).eq('id', recipient.recipientId);
        return { sent: true, failed: true, retry: false };
      }

      const formattedPhone = formatPhoneNumber(recipient.phone);
      const resolvedRecipientName = (() => {
        if (recipient.name && !isAutoGeneratedLeadName(recipient.name)) {
          return recipient.name;
        }

        if (recipient.leadId) {
          const leadName = leadNameById.get(recipient.leadId);
          if (leadName && !isAutoGeneratedLeadName(leadName)) {
            return leadName;
          }
        }

        for (const key of getPhoneLookupKeys(formattedPhone)) {
          const leadName = leadNameByPhoneKey.get(key);
          if (leadName && !isAutoGeneratedLeadName(leadName)) {
            return leadName;
          }
        }

        return null;
      })();

      const templateParams: string[] = [];
      if (template.variables && template.variables.length > 0) {
        for (const varName of template.variables) {
          const mapping = template.variable_mappings?.[varName] || 'manual';
          let value = '';
          if (mapping === 'contact_first_name') {
            value = getFirstName(resolvedRecipientName || undefined) || resolvedRecipientName || 'Cliente';
          } else if (mapping === 'contact_name' || mapping === 'contact_full_name') {
            value = resolvedRecipientName || 'Cliente';
          } else if (mapping.startsWith('custom_field:')) {
            // Resolve custom field from lead's custom_fields JSONB
            const fieldName = mapping.replace('custom_field:', '');
            let customFields: Record<string, any> | undefined;
            if (recipient.leadId) {
              customFields = leadCustomFieldsMap.get(recipient.leadId);
            }
            // Fallback: lookup by phone keys when leadId is missing or didn't resolve the field
            if (!customFields || customFields[fieldName] === undefined || customFields[fieldName] === null || customFields[fieldName] === '') {
              for (const key of getPhoneLookupKeys(formattedPhone)) {
                const candidate = leadCustomFieldsByPhoneKey.get(key);
                if (candidate && candidate[fieldName] !== undefined && candidate[fieldName] !== null && candidate[fieldName] !== '') {
                  customFields = candidate;
                  break;
                }
              }
            }
            value = customFields?.[fieldName] ? String(customFields[fieldName]) : '';
          } else if (variableFieldMap[mapping]) {
            const field = variableFieldMap[mapping] as keyof Recipient;
            value = String((recipient as unknown as Recipient)[field] || '');
          } else if (mapping === 'manual' && manualVariables) {
            const possibleKeys = [
              varName, varName.replace(/^VAR_/, 'p'), varName.replace(/^p/, 'VAR_'),
              `VAR_${varName.replace(/\D/g, '')}`, `p${varName.replace(/\D/g, '')}`,
              varName.toLowerCase(), varName.toUpperCase(),
            ];
            for (const key of possibleKeys) {
              if (manualVariables[key] !== undefined && manualVariables[key] !== '') {
                value = manualVariables[key]; break;
              }
            }
            if (!value) {
              const keys = Object.keys(manualVariables);
              const varIndex = template.variables.indexOf(varName);
              if (varIndex >= 0 && varIndex < keys.length) {
                value = manualVariables[keys[varIndex]] || '';
              }
            }
          }
          if (value.match(/^(VAR_\d+|p\d+)$/i)) value = '';
          // Ensure no empty params - use fallback to prevent Meta rejection
          if (!value.trim()) value = 'Cliente';
          templateParams.push(value);
        }
      }

      // Detect Lovable/edge-runtime rate-limit errors so we recycle to pending
      // instead of permanently marking the recipient as failed.
      const isRateLimitError = (status: number | null, msg: string | null | undefined): boolean => {
        if (status === 429) return true;
        if (!msg) return false;
        const s = String(msg);
        return /rate\s*limit/i.test(s) || /RateLimitError/i.test(s) || /too many requests/i.test(s);
      };

      const recycleToPending = async (reason: string) => {
        // Recycle: send back to pending so campaign keeps moving. Don't count as failure.
        // Small backoff so we don't immediately re-trip the same per-trace bucket.
        await supabase.from('campaign_recipients').update({
          status: 'pending',
          error_message: reason,
          last_error_code: 'RATE_LIMIT',
          next_retry_at: new Date(Date.now() + 65_000).toISOString(),
          channel_id: channel.id
        }).eq('id', recipient.recipientId);
        return { sent: false, failed: false, retry: true };
      };

      const sendController = new AbortController();
      const sendTimeout = setTimeout(() => sendController.abort(), 25000);
      try {
        const response = await fetch(`${metaSendUrl}/functions/v1/meta-send`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${metaSendKey}` },
          body: JSON.stringify({
            channelId: channel.id, destination: formattedPhone, templateName: template.name,
            templateParams: templateParams.length > 0 ? templateParams : undefined,
            campaignId: campaignId
          }),
          signal: sendController.signal,
        });
        clearTimeout(sendTimeout);

        // Edge-runtime rate limit (429) — recycle without marking failed
        if (response.status === 429) {
          const text = await response.text().catch(() => 'Rate limit');
          return await recycleToPending(text.slice(0, 200) || 'Rate limit (429)');
        }

        const result = await response.json().catch(() => ({ success: false, error: `HTTP ${response.status}` }));

        if (result.success) {
          await supabase.from('campaign_recipients').update({
            status: 'sent', sent_at: new Date().toISOString(), error_message: null, last_error_code: null, next_retry_at: null,
            channel_id: channel.id
          }).eq('id', recipient.recipientId);

          // Update conversation assignment — NEVER overwrite active conversations (external SSoT)
          const { data: existing } = await caDb.from('conversation_assignments').select('id, status')
            .eq('conversation_phone', formattedPhone).eq('channel_id', channel.id).single();
          if (existing) {
            const updatePayload: Record<string, unknown> = {
              organization_id: channel.organization_id,
              campaign_chatbot_id: campaign.chatbot_enabled && campaign.chatbot_id ? campaign.chatbot_id : null,
              is_bot_handling: campaign.chatbot_enabled && !!campaign.chatbot_id,
              sector_id: campaign.sector_id || null,
              updated_at: new Date().toISOString()
            };
            // Only set archived if not already active (in_progress/pending)
            if (existing.status !== 'in_progress' && existing.status !== 'pending') {
              updatePayload.status = 'archived';
            }
            await caDb.from('conversation_assignments').update(updatePayload).eq('id', existing.id);
          } else {
            await caDb.from('conversation_assignments').insert({
              organization_id: channel.organization_id,
              conversation_phone: formattedPhone, channel_id: channel.id,
              campaign_chatbot_id: campaign.chatbot_enabled && campaign.chatbot_id ? campaign.chatbot_id : null,
              is_bot_handling: campaign.chatbot_enabled && !!campaign.chatbot_id,
              status: 'archived', sector_id: campaign.sector_id || null
            });
          }
          return { sent: !recipient.isRetry, failed: false, retry: false };
        } else {
          // Rate limit returned as success=false body — recycle, don't mark failed
          if (isRateLimitError(response.status, result.error)) {
            return await recycleToPending(String(result.error || 'Rate limit').slice(0, 200));
          }

          const rawErrorCode = result.errorCode ?? extractMetaErrorCode(result.error || '');
          const errorCode = rawErrorCode ? String(rawErrorCode) : null;

          await supabase.from('campaign_recipients').update({
            status: 'failed', error_message: result.error || 'Erro desconhecido', last_error_code: errorCode || 'UNKNOWN',
            channel_id: channel.id
          }).eq('id', recipient.recipientId);
          return { sent: !recipient.isRetry, failed: true, retry: false };
        }
      } catch (error) {
        const errorMessage = String(error);
        // Network/transport rate-limit (thrown by runtime) — recycle to pending
        if (isRateLimitError(null, errorMessage)) {
          return await recycleToPending(errorMessage.slice(0, 200));
        }
        await supabase.from('campaign_recipients').update({
          status: 'failed',
          error_message: errorMessage,
          last_error_code: 'EXCEPTION',
          channel_id: channel.id
        }).eq('id', recipient.recipientId);
        return { sent: !recipient.isRetry, failed: true, retry: false };
      }
    }

    // Process all recipients in PARALLEL
    const results = await Promise.all(
      recipientsToSend.map((recipient: any, i: number) => processRecipient(recipient, campaign.sent_count + i))
    );

    for (const r of results) {
      if (r.sent) sentThisBatch++;
      if (r.failed) failedThisBatch++;
      if (r.retry) scheduledRetryThisBatch++;
    }

    // Get accurate counts from DB
    let fc = await getCounts();
    let hasPending = (Number(fc.total_pending) || 0) > 0;
    let hasProcessing = (Number(fc.total_processing) || 0) > 0;
    let hasRetries = (Number(fc.total_waiting_retry) || 0) > 0;

    if (!hasPending && !hasProcessing) {
      const recoveredFailed = await recoverFailedRecipients();
      if (recoveredFailed > 0) {
        const recoveredCounts = await getCounts();
        await persistCampaignState(recoveredCounts, 'running');

        return new Response(
          JSON.stringify({
            success: true,
            done: false,
            status: 'running',
            sent: Number(recoveredCounts.total_sent) || 0,
            delivered: Number(recoveredCounts.total_delivered) || 0,
            failed: Number(recoveredCounts.total_failed) || 0,
            total: campaign.total_recipients,
            batchProcessed: sentThisBatch,
            scheduledRetries: scheduledRetryThisBatch,
            recoveredFailed,
            pendingRetries: Number(recoveredCounts.total_waiting_retry) || 0
          }),
          { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
      }
    }

    fc = await getCounts();
    const actualRecipientTotal = await getRecipientTotal();
    hasPending = (Number(fc.total_pending) || 0) > 0;
    hasProcessing = (Number(fc.total_processing) || 0) > 0;
    hasRetries = (Number(fc.total_waiting_retry) || 0) > 0;
    const totalTerminal = (Number(fc.total_sent) || 0) + (Number(fc.total_failed) || 0);
    const completionTarget = actualRecipientTotal || campaign.total_recipients;
    const isComplete = !hasPending && !hasProcessing && !hasRetries && totalTerminal >= completionTarget;

    const newStatus = isComplete ? 'completed' : 'running';
    await persistCampaignState(fc, newStatus, actualRecipientTotal || undefined);

    console.log(`[Batch] Campaign ${campaign.name}: sent=${fc.total_sent}, failed=${fc.total_failed}, pending=${fc.total_pending}, retry=${fc.total_waiting_retry}, processing=${fc.total_processing}`);

    return new Response(
      JSON.stringify({
        success: true,
        done: isComplete,
        status: isComplete ? 'completed' : (hasRetries && !hasPending ? 'waiting_retry' : 'running'),
        sent: Number(fc.total_sent) || 0,
        delivered: Number(fc.total_delivered) || 0,
        failed: Number(fc.total_failed) || 0,
        total: actualRecipientTotal || campaign.total_recipients,
        batchProcessed: sentThisBatch,
        scheduledRetries: scheduledRetryThisBatch,
        pendingRetries: Number(fc.total_waiting_retry) || 0
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error('[Batch] Error:', error);
    return new Response(
      JSON.stringify({ error: String(error) }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
