import { useState, useEffect, useCallback, useRef, useMemo } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { useEffectiveOrganizationId } from "@/hooks/useEffectiveOrganizationId";

export interface Conversation {
  id: string; // conversation_assignment id
  phone: string;
  name: string | null;
  lastMessage: string;
  lastMessageTime: string;
  lastInboundTime: string | null;
  unreadCount: number;
  channelId: string | null;
  status: "pending" | "in_progress" | "resolved" | "archived" | "active";
  assignedTo: string | null;
  assignedToName: string | null;
  sectorId: string | null;
  tags: string[] | null;
  leadId: string | null;
}

export interface Channel {
  id: string;
  name: string;
  phone: string;
  provider: string;
}

interface UseConversationsOptions {
  channels: Channel[];
  sectorIds: string[];
  canSeeSector: (sectorId: string | null) => boolean;
}

interface LeadInfo {
  name: string;
  tags: string[] | null;
}

export function useConversations({ channels, sectorIds, canSeeSector }: UseConversationsOptions) {
  const { user } = useAuth();
  const { effectiveOrganizationId } = useEffectiveOrganizationId();
  
  const [allConversations, setAllConversations] = useState<Conversation[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchingGlobal, setSearchingGlobal] = useState(false);
  
  // Maps for quick lookups
  const leadsMapRef = useRef<{
    byPhone: Map<string, LeadInfo>;
    bySuffix: Map<string, LeadInfo>;
  }>({ byPhone: new Map(), bySuffix: new Map() });
  
  const profilesMapRef = useRef<Map<string, string>>(new Map());

  // Filter conversations based on sector access
  const conversations = useMemo(() => 
    allConversations.filter(c => canSeeSector(c.sectorId)),
    [allConversations, canSeeSector]
  );

  // Fetch conversations using conversation_assignments as primary source
  const fetchConversations = useCallback(async () => {
    if (channels.length === 0 || !effectiveOrganizationId) {
      setLoading(false);
      return;
    }

    setLoading(true);
    const channelIds = channels.map(c => c.id);

    try {
      // Parallel fetches - using conversation_assignments as PRIMARY source
      const [assignmentsResult, profilesResult, leadsResult] = await Promise.all([
        supabase
          .from("conversation_assignments")
          .select("id, conversation_phone, channel_id, assigned_to, status, sector_id, lead_id, updated_at")
          .in("channel_id", channelIds)
          .order("updated_at", { ascending: false }),
        supabase
          .from("profiles")
          .select("user_id, display_name, email"),
        supabase
          .from("leads")
          .select("id, phone, name, tags")
          .eq("organization_id", effectiveOrganizationId)
      ]);

      if (assignmentsResult.error) {
        console.error("Error fetching assignments:", assignmentsResult.error);
        setLoading(false);
        return;
      }

      // Build leads map - ALWAYS prioritize database name over WhatsApp profile name
      const leadsMap = new Map<string, LeadInfo>();
      const leadsBySuffix = new Map<string, LeadInfo>();
      const leadsById = new Map<string, LeadInfo & { phone: string }>();

      leadsResult.data?.forEach((lead) => {
        const normalizedPhone = lead.phone.replace(/\D/g, '');
        const isAutoGenerated = lead.name?.startsWith('LeadWhats-') || lead.name?.startsWith('WhatsApp ');
        const phoneSuffix8 = normalizedPhone.slice(-8);
        const phoneSuffix9 = normalizedPhone.slice(-9);

        const leadData: LeadInfo = {
          name: isAutoGenerated ? '' : (lead.name || ''),
          tags: lead.tags && lead.tags.length > 0 ? lead.tags : null
        };

        leadsById.set(lead.id, { ...leadData, phone: normalizedPhone });
        
        // CRITICAL FIX: Store ALL leads by phone, not just those with name/tags
        // This ensures we can always find the lead by phone matching
        // The name field being empty will trigger WhatsApp fallback, but having
        // the lead in the map allows proper priority logic later
        
        // Store by normalized phone (with all formats for maximum matching)
        leadsMap.set(normalizedPhone, leadData);
        const phoneWithout55 = normalizedPhone.startsWith('55') ? normalizedPhone.slice(2) : normalizedPhone;
        const phoneWith55 = normalizedPhone.startsWith('55') ? normalizedPhone : `55${normalizedPhone}`;
        leadsMap.set(phoneWithout55, leadData);
        leadsMap.set(phoneWith55, leadData);
        
        // Store by suffix for fallback matching (8 and 9 digit suffixes)
        // Prioritize leads with real names over auto-generated ones
        const existing8 = leadsBySuffix.get(phoneSuffix8);
        if (!existing8 || (!existing8.name && leadData.name) || 
            (leadData.name && !isAutoGenerated && (!existing8.name || existing8.name.startsWith('LeadWhats-')))) {
          leadsBySuffix.set(phoneSuffix8, leadData);
        }
        
        // Also store by 9-digit suffix for better matching with Brazilian numbers
        const existing9 = leadsBySuffix.get(phoneSuffix9);
        if (!existing9 || (!existing9.name && leadData.name) ||
            (leadData.name && !isAutoGenerated && (!existing9.name || existing9.name.startsWith('LeadWhats-')))) {
          leadsBySuffix.set(phoneSuffix9, leadData);
        }
      });

      leadsMapRef.current = { byPhone: leadsMap, bySuffix: leadsBySuffix };

      // Build profiles map
      const profilesMap = new Map<string, string>();
      profilesResult.data?.forEach((profile) => {
        profilesMap.set(profile.user_id, profile.display_name || profile.email || 'Atendente');
      });
      profilesMapRef.current = profilesMap;

      // Fetch last message for each conversation (batch query)
      const conversationPhones = assignmentsResult.data?.map(a => ({
        channelId: a.channel_id,
        phone: a.conversation_phone.replace(/\D/g, '')
      })) || [];

      // Get last messages for all conversations in one query
      const lastMessagesPromises = channelIds.map(channelId => 
        supabase
          .from("whatsapp_messages")
          .select("channel_id, sender_phone, content, created_at, direction, metadata, is_read")
          .eq("channel_id", channelId)
          .order("created_at", { ascending: false })
          .limit(500)
      );

      const lastMessagesResults = await Promise.all(lastMessagesPromises);
      
      // Build messages map by conversation key
      const lastMessagesByConv = new Map<string, {
        content: string;
        createdAt: string;
        lastInboundTime: string | null;
        unreadCount: number;
        senderName: string | null;
      }>();

      lastMessagesResults.forEach(result => {
        if (result.error || !result.data) return;
        
        result.data.forEach(msg => {
          let contactPhone: string;
          
          if (msg.direction === "inbound") {
            contactPhone = msg.sender_phone.replace(/\D/g, '');
          } else {
            const metadata = msg.metadata as { destination?: string } | null;
            contactPhone = (metadata?.destination || '').replace(/\D/g, '');
            if (!contactPhone) return;
          }

          const key = `${msg.channel_id}_${contactPhone}`;
          const existing = lastMessagesByConv.get(key);

          if (!existing) {
            lastMessagesByConv.set(key, {
              content: msg.content || '',
              createdAt: msg.created_at,
              lastInboundTime: msg.direction === 'inbound' ? msg.created_at : null,
              unreadCount: msg.direction === 'inbound' && !msg.is_read ? 1 : 0,
              senderName: msg.direction === 'inbound' ? (msg as { sender_name?: string }).sender_name || null : null
            });
          } else {
            // Update last inbound time if this is an inbound message
            if (msg.direction === 'inbound') {
              if (!existing.lastInboundTime || new Date(msg.created_at) > new Date(existing.lastInboundTime)) {
                existing.lastInboundTime = msg.created_at;
              }
              if (!msg.is_read) {
                existing.unreadCount++;
              }
            }
          }
        });
      });

      // Build conversations from assignments
      const conversationsFromAssignments: Conversation[] = (assignmentsResult.data || []).map(assignment => {
        const normalizedPhone = assignment.conversation_phone.replace(/\D/g, '');
        const conversationKey = `${assignment.channel_id}_${normalizedPhone}`;
        const displayPhone = normalizedPhone.startsWith('+') ? normalizedPhone : '+' + normalizedPhone;

        // Get lead info
        let leadInfo: LeadInfo | undefined;
        
        // First try by lead_id
        if (assignment.lead_id) {
          const leadById = leadsById.get(assignment.lead_id);
          if (leadById) {
            leadInfo = { name: leadById.name, tags: leadById.tags };
          }
        }

        // Fallback to phone matching - try multiple suffix lengths for better matching
        if (!leadInfo || !leadInfo.name) {
          const phoneSuffix8 = normalizedPhone.slice(-8);
          const phoneSuffix9 = normalizedPhone.slice(-9);
          
          // Try by full phone first, then by suffix (9 digits, then 8 digits)
          const byFullPhone = leadsMap.get(normalizedPhone);
          const bySuffix9 = leadsBySuffix.get(phoneSuffix9);
          const bySuffix8 = leadsBySuffix.get(phoneSuffix8);
          
          // Prioritize matches with real names
          const candidates = [byFullPhone, bySuffix9, bySuffix8].filter(Boolean);
          const bestMatch = candidates.find(c => c && c.name && !c.name.startsWith('LeadWhats-')) || candidates[0];
          
          if (bestMatch) {
            // Only update if the new match has a better name
            if (!leadInfo || !leadInfo.name || (bestMatch.name && !bestMatch.name.startsWith('LeadWhats-'))) {
              leadInfo = bestMatch;
            }
          }
        }

        // Get last message info
        const lastMsgInfo = lastMessagesByConv.get(conversationKey);

        // Map status from DB to frontend
        let mappedStatus: Conversation["status"] = "pending";
        if (assignment.status === "active" || assignment.status === "in_progress") mappedStatus = "in_progress";
        else if (assignment.status === "archived") mappedStatus = "archived";
        else if (assignment.status === "resolved") mappedStatus = "resolved";
        else if (assignment.status === "pending") mappedStatus = "pending";

        return {
          id: assignment.id,
          phone: displayPhone,
          name: leadInfo?.name || lastMsgInfo?.senderName || null,
          lastMessage: lastMsgInfo?.content || "",
          lastMessageTime: lastMsgInfo?.createdAt || assignment.updated_at,
          lastInboundTime: lastMsgInfo?.lastInboundTime || null,
          unreadCount: lastMsgInfo?.unreadCount || 0,
          channelId: assignment.channel_id,
          status: mappedStatus,
          assignedTo: assignment.assigned_to,
          assignedToName: assignment.assigned_to ? profilesMap.get(assignment.assigned_to) || null : null,
          sectorId: assignment.sector_id,
          tags: leadInfo?.tags || null,
          leadId: assignment.lead_id
        };
      });

      // Sort by last message time
      conversationsFromAssignments.sort((a, b) => 
        new Date(b.lastMessageTime).getTime() - new Date(a.lastMessageTime).getTime()
      );

      setAllConversations(conversationsFromAssignments);
      setLoading(false);

    } catch (error) {
      console.error("Error fetching conversations:", error);
      setLoading(false);
    }
  }, [channels, effectiveOrganizationId]);

  // Global search that queries the database directly
  const searchConversationsGlobal = useCallback(async (searchTerm: string): Promise<Conversation[]> => {
    if (!searchTerm.trim() || channels.length === 0 || !effectiveOrganizationId) {
      return [];
    }

    setSearchingGlobal(true);
    const channelIds = channels.map(c => c.id);
    const normalizedSearch = searchTerm.replace(/\D/g, '');
    
    try {
      // Search in conversation_assignments by phone
      const { data: assignments, error } = await supabase
        .from("conversation_assignments")
        .select("id, conversation_phone, channel_id, assigned_to, status, sector_id, lead_id, updated_at")
        .in("channel_id", channelIds)
        .or(`conversation_phone.ilike.%${normalizedSearch}%,conversation_phone.ilike.%${searchTerm}%`)
        .order("updated_at", { ascending: false })
        .limit(50);

      if (error || !assignments) {
        setSearchingGlobal(false);
        return [];
      }

      // Also search leads by name
      const { data: leadsByName } = await supabase
        .from("leads")
        .select("id, phone, name, tags")
        .eq("organization_id", effectiveOrganizationId)
        .ilike("name", `%${searchTerm}%`)
        .limit(50);

      // Find assignments for these leads
      const leadPhones = (leadsByName || []).map(l => l.phone.replace(/\D/g, ''));
      
      let additionalAssignments: typeof assignments = [];
      if (leadPhones.length > 0) {
        const phoneConditions = leadPhones.map(p => `conversation_phone.ilike.%${p.slice(-8)}%`).join(',');
        const { data: byLeadPhone } = await supabase
          .from("conversation_assignments")
          .select("id, conversation_phone, channel_id, assigned_to, status, sector_id, lead_id, updated_at")
          .in("channel_id", channelIds)
          .or(phoneConditions)
          .order("updated_at", { ascending: false })
          .limit(50);
        
        additionalAssignments = byLeadPhone || [];
      }

      // Combine and deduplicate
      const allAssignments = [...assignments, ...additionalAssignments];
      const uniqueAssignments = allAssignments.filter((a, idx, self) => 
        idx === self.findIndex(b => b.id === a.id)
      );

      // Build conversations
      const searchResults: Conversation[] = uniqueAssignments.map(assignment => {
        const normalizedPhone = assignment.conversation_phone.replace(/\D/g, '');
        const displayPhone = normalizedPhone.startsWith('+') ? normalizedPhone : '+' + normalizedPhone;

        // Find matching lead
        const matchingLead = (leadsByName || []).find(l => 
          l.phone.replace(/\D/g, '').slice(-8) === normalizedPhone.slice(-8)
        );

        let mappedStatus: Conversation["status"] = "pending";
        if (assignment.status === "active" || assignment.status === "in_progress") mappedStatus = "in_progress";
        else if (assignment.status === "archived") mappedStatus = "archived";
        else if (assignment.status === "resolved") mappedStatus = "resolved";

        return {
          id: assignment.id,
          phone: displayPhone,
          name: matchingLead?.name || null,
          lastMessage: "",
          lastMessageTime: assignment.updated_at,
          lastInboundTime: null,
          unreadCount: 0,
          channelId: assignment.channel_id,
          status: mappedStatus,
          assignedTo: assignment.assigned_to,
          assignedToName: assignment.assigned_to ? profilesMapRef.current.get(assignment.assigned_to) || null : null,
          sectorId: assignment.sector_id,
          tags: matchingLead?.tags || null,
          leadId: assignment.lead_id
        };
      });

      setSearchingGlobal(false);
      return searchResults;

    } catch (error) {
      console.error("Error searching conversations:", error);
      setSearchingGlobal(false);
      return [];
    }
  }, [channels, effectiveOrganizationId]);

  // Update a conversation in the list
  const updateConversation = useCallback((conversationId: string, updates: Partial<Conversation>) => {
    setAllConversations(prev => prev.map(c => 
      c.id === conversationId ? { ...c, ...updates } : c
    ));
  }, []);

  // Add a new conversation
  const addConversation = useCallback((conversation: Conversation) => {
    setAllConversations(prev => {
      const exists = prev.some(c => c.id === conversation.id);
      if (exists) {
        return prev.map(c => c.id === conversation.id ? conversation : c);
      }
      return [conversation, ...prev];
    });
  }, []);

  // Get conversation key for compatibility
  const getConversationKey = useCallback((conv: Conversation) => {
    return `${conv.channelId || 'unknown'}_${conv.phone.replace(/\D/g, '')}`;
  }, []);

  // Initial fetch
  useEffect(() => {
    fetchConversations();
  }, [fetchConversations]);

  return {
    conversations,
    allConversations,
    loading,
    searchingGlobal,
    fetchConversations,
    searchConversationsGlobal,
    updateConversation,
    addConversation,
    getConversationKey,
    leadsMapRef,
    profilesMapRef
  };
}
