import { useState, useEffect, useCallback, useMemo } from "react";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { 
  Send, 
  Plus, 
  Calendar,
  Users,
  MessageSquare,
  Clock,
  CheckCircle,
  XCircle,
  MoreVertical,
  Play,
  Pause,
  ArrowLeft,
  Settings2,
  Check,
  Shuffle,
  Timer,
  Smartphone,
  Eye,
  RefreshCw,
  Bot,
  RotateCcw,
  AlertTriangle
} from "lucide-react";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";
import { MainLayout } from "@/components/layout/MainLayout";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { 
  Table, 
  TableBody, 
  TableCell, 
  TableHead, 
  TableHeader, 
  TableRow 
} from "@/components/ui/table";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";
import { cn } from "@/lib/utils";
import { supabase } from "@/integrations/supabase/client";
import { fetchAllLeads } from "@/lib/fetchAllLeads";
import { useAuth } from "@/hooks/useAuth";
import { useEffectiveOrganizationId } from "@/hooks/useEffectiveOrganizationId";
import { useUserSectors } from "@/hooks/useUserSectors";
import { useUserRole } from "@/hooks/useUserRole";
import { toast } from "sonner";
import { CampaignDetailsDialog } from "@/components/campaigns/CampaignDetailsDialog";
import { CampaignReportDialog } from "@/components/campaigns/CampaignReportDialog";
import { CampaignProgressBar } from "@/components/campaigns/CampaignProgressBar";
import { RecipientSelection } from "@/components/campaigns/RecipientSelection";
import { RecycleFailuresDialog } from "@/components/campaigns/RecycleFailuresDialog";
import { ChannelSelectionByAccount } from "@/components/campaigns/ChannelSelectionByAccount";
import { useCampaignProcessor } from "@/hooks/useCampaignProcessor";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";

interface Channel {
  id: string;
  name: string;
  phone: string;
  provider: string;
  connected: boolean;
  waba_id?: string | null;
  app_name?: string | null;
}

interface MessageTemplate {
  id: string;
  name: string;
  content: string;
  variables?: string[] | null;
  variable_mappings?: Record<string, string> | null;
  dispatch_type?: string | null;
}

interface ChannelTemplate {
  channel_id: string;
  template_id: string;
}

interface AIAgent {
  id: string;
  name: string;
  is_active: boolean;
}

interface Campaign {
  id: string;
  name: string;
  status: "draft" | "scheduled" | "running" | "paused" | "completed" | "failed";
  total_recipients: number;
  sent_count: number;
  delivered_count: number;
  failed_count: number;
  scheduled_at?: string | null;
  created_at: string;
  updated_at: string;
  started_at?: string | null;
  completed_at?: string | null;
  min_interval?: number;
  max_interval?: number;
  sector_id?: string | null;
  chatbot_enabled?: boolean;
  organization_id?: string | null;
}

const statusConfig: Record<string, { label: string; className: string; icon: typeof MessageSquare }> = {
  draft: { label: "Rascunho", className: "bg-muted text-muted-foreground border-border", icon: MessageSquare },
  scheduled: { label: "Agendada", className: "bg-warning/10 text-warning border-warning/30", icon: Clock },
  running: { label: "Enviando", className: "bg-blue-500/10 text-blue-400 border-blue-400/30", icon: Play },
  paused: { label: "Pausada", className: "bg-yellow-500/10 text-yellow-400 border-yellow-400/30", icon: Pause },
  completed: { label: "Concluída", className: "bg-primary/10 text-primary border-primary/30", icon: CheckCircle },
  failed: { label: "Falhou", className: "bg-destructive/10 text-destructive border-destructive/30", icon: XCircle },
};

interface Sector {
  id: string;
  name: string;
  description: string | null;
}

interface LeadMatch {
  id: string;
  name: string | null;
  isAutoGenerated: boolean;
}

const isAutoGeneratedLeadName = (name?: string | null) =>
  !name || name.startsWith("LeadWhats-") || name.startsWith("WhatsApp ");

const getPhoneLookupKeys = (phone: string): string[] => {
  const digits = phone.replace(/\D/g, "");
  if (!digits) return [];

  const withoutCountryCode = digits.startsWith("55") ? digits.slice(2) : digits;

  return [...new Set([
    digits,
    withoutCountryCode,
    withoutCountryCode.slice(-9),
    withoutCountryCode.slice(-8),
  ].filter(Boolean))];
};

const chooseBetterLeadMatch = (current: LeadMatch | undefined, candidate: LeadMatch): LeadMatch => {
  if (!current) return candidate;

  if (!current.name && candidate.name) return candidate;
  if (current.isAutoGenerated && !candidate.isAutoGenerated) return candidate;

  return current;
};

const Disparos = () => {
  const { user } = useAuth();
  const { effectiveOrganizationId } = useEffectiveOrganizationId();
  const { canSeeSector, hasFullAccess } = useUserSectors();
  const { role } = useUserRole();
  const [showCreateForm, setShowCreateForm] = useState(false);
  const [channels, setChannels] = useState<Channel[]>([]);
  const [templates, setTemplates] = useState<MessageTemplate[]>([]);
  const [channelTemplateRelations, setChannelTemplateRelations] = useState<ChannelTemplate[]>([]);
  const [allCampaigns, setAllCampaigns] = useState<Campaign[]>([]);
  const [aiAgents, setAiAgents] = useState<AIAgent[]>([]);
  const [sectors, setSectors] = useState<Sector[]>([]);
  const [loading, setLoading] = useState(true);
  const [isCreating, setIsCreating] = useState(false);
  const [selectedCampaign, setSelectedCampaign] = useState<Campaign | null>(null);
  const [showDetailsDialog, setShowDetailsDialog] = useState(false);
  const [showReportDialog, setShowReportDialog] = useState(false);
  const [showRecycleDialog, setShowRecycleDialog] = useState(false);
  const [recyclingCampaign, setRecyclingCampaign] = useState<Campaign | null>(null);
  
  // Filter campaigns based on user's sector access
  const campaigns = allCampaigns.filter(c => canSeeSector(c.sector_id ?? null));
  
  const [selectedChannels, setSelectedChannels] = useState<string[]>([]);
  const [channelTemplates, setChannelTemplates] = useState<Record<string, string>>({});
  type TemplateMode = 'template_unified' | 'template_per_channel' | 'flow';
  const [templateMode, setTemplateMode] = useState<TemplateMode>('template_unified');
  const useUnifiedTemplate = templateMode === 'template_unified';
  const useFlowMode = templateMode === 'flow';
  const setUseUnifiedTemplate = (v: boolean) => setTemplateMode(v ? 'template_unified' : 'template_per_channel');
  // Dispatch flows (flow_bots with flow_type = 'dispatch')
  const [dispatchFlows, setDispatchFlows] = useState<Array<{ id: string; name: string; template_id: string | null }>>([]);
  const [selectedFlowId, setSelectedFlowId] = useState<string>("");
  const [channelFlows, setChannelFlows] = useState<Record<string, string>>({});
  const [recipientData, setRecipientData] = useState<{ phones: string[]; source: "contacts" | "numbers" | null }>({
    phones: [],
    source: null
  });
  const [manualVariables, setManualVariables] = useState<Record<string, string>>({});
  const [channelManualVariables, setChannelManualVariables] = useState<Record<string, Record<string, string>>>({});
  const [formData, setFormData] = useState({
    campaignName: "",
    department: "",
    chatbot: "disabled",
    chatbotSource: "channel" as "channel" | "custom",
    selectedChatbotId: "",
    startTime: "now",
    scheduledDate: "",
    scheduledTime: "",
    unifiedTemplate: "",
    cadenceType: "standard" as "standard" | "warmup" | "full",
    minInterval: "5",
    maxInterval: "90"
  });

  // Memoized fetchData callback
  const fetchData = useCallback(async () => {
    if (!effectiveOrganizationId) return;
    setLoading(true);

    // Fetch channels - exclude Z-API channels (they can't be used for mass dispatches)
    const { data: channelsData } = await supabase
      .from("channels")
      .select("id, name, phone, provider, connected, waba_id, app_name")
      .eq("organization_id", effectiveOrganizationId)
      .eq("connected", true)
      .neq("provider", "zapi");

    // Fetch templates (only approved ones for dispatching)
    const { data: templatesData } = await supabase
      .from("message_templates")
      .select("id, name, content, variables, variable_mappings")
      .eq("organization_id", effectiveOrganizationId)
      .eq("status", "approved");

    // Fetch channel-template relations
    const { data: ctData } = await supabase
      .from("channel_templates")
      .select("channel_id, template_id");

    // Fetch campaigns
    const { data: campaignsData } = await supabase
      .from("campaigns")
      .select("*")
      .eq("organization_id", effectiveOrganizationId)
      .order("created_at", { ascending: false });

    // Fetch AI agents
    const { data: agentsData } = await supabase
      .from("ai_agents")
      .select("id, name, is_active")
      .eq("organization_id", effectiveOrganizationId)
      .eq("is_active", true);

    // Fetch sectors/departments
    const { data: sectorsData } = await supabase
      .from("sectors")
      .select("id, name, description")
      .eq("organization_id", effectiveOrganizationId)
      .order("name");

    // Fetch dispatch flows (flow_bots configured for campaign dispatch)
    const { data: dispatchFlowsData } = await supabase
      .from("flow_bots")
      .select("id, name, template_id, flow_type, is_active")
      .eq("organization_id", effectiveOrganizationId)
      .eq("flow_type", "dispatch")
      .eq("is_active", true)
      .not("template_id", "is", null);
    setDispatchFlows((dispatchFlowsData || []).map((f: any) => ({
      id: f.id,
      name: f.name,
      template_id: f.template_id,
    })));

    // Combine real data with demo data
    const realChannels = channelsData || [];
    const realTemplates = templatesData || [];
    const realRelations = ctData || [];

    const demoChannel: Channel = {
      id: "demo-channel-1",
      name: "WhatsApp Vendas (Demo)",
      phone: "+5511999999999",
      provider: "meta",
      connected: true
    };

    const demoTemplates: MessageTemplate[] = [
      {
        id: "demo-template-1",
        name: "Boas-vindas",
        content: "Olá {{nome}}! 👋 Seja bem-vindo(a) à nossa empresa. Estamos felizes em tê-lo conosco!",
        variables: null,
        variable_mappings: null
      },
      {
        id: "demo-template-2", 
        name: "Promoção Especial",
        content: "🎉 {{nome}}, temos uma oferta exclusiva para você! Aproveite 20% de desconto usando o cupom PROMO20.",
        variables: null,
        variable_mappings: null
      },
      {
        id: "demo-template-3",
        name: "Lembrete de Agendamento",
        content: "📅 Olá {{nome}}, lembrando do seu agendamento amanhã às {{horario}}. Confirme sua presença!",
        variables: null,
        variable_mappings: null
      }
    ];

    const demoChannelTemplateRelations: ChannelTemplate[] = [
      { channel_id: "demo-channel-1", template_id: "demo-template-1" },
      { channel_id: "demo-channel-1", template_id: "demo-template-2" },
      { channel_id: "demo-channel-1", template_id: "demo-template-3" }
    ];

    setChannels([demoChannel, ...realChannels]);
    setTemplates([...demoTemplates, ...realTemplates.map(t => ({
      ...t,
      variable_mappings: t.variable_mappings as Record<string, string> | null
    }))]);
    setChannelTemplateRelations([...demoChannelTemplateRelations, ...realRelations]);
    // Fetch real counters derived from campaign_recipients to fix stale aggregates in campaigns table
    const campaignIds = (campaignsData || []).map(c => c.id);
    let realCountsMap = new Map<string, { sent: number; delivered: number; failed: number }>();
    if (campaignIds.length > 0) {
      const { data: realCounts, error: realCountsError } = await supabase
        .rpc("get_campaign_real_counts", { p_campaign_ids: campaignIds });
      if (realCountsError) {
        console.warn("[Disparos] get_campaign_real_counts failed, falling back to stored counters", realCountsError);
      } else if (realCounts) {
        for (const row of realCounts as Array<{ campaign_id: string; sent_count: number; delivered_count: number; failed_count: number }>) {
          realCountsMap.set(row.campaign_id, {
            sent: Number(row.sent_count) || 0,
            delivered: Number(row.delivered_count) || 0,
            failed: Number(row.failed_count) || 0,
          });
        }
      }
    }

    setAllCampaigns((campaignsData || []).map(c => {
      const real = realCountsMap.get(c.id);
      return {
        ...c,
        status: c.status as Campaign["status"],
        // Prefer real counters from campaign_recipients (source of truth) when available.
        sent_count: real ? real.sent : c.sent_count,
        delivered_count: real ? real.delivered : c.delivered_count,
        failed_count: real ? real.failed : c.failed_count,
      };
    }));
    setAiAgents(agentsData || []);
    setSectors(sectorsData || []);
    setLoading(false);
  }, [effectiveOrganizationId]);

  useEffect(() => {
    // Reset campaigns immediately when org changes to avoid showing previous org's data
    setAllCampaigns([]);
    setLoading(true);
    if (user && effectiveOrganizationId) {
      fetchData();
    }
  }, [user, effectiveOrganizationId, fetchData]);

  // Realtime subscription for campaigns and campaign_recipients updates
  useEffect(() => {
    if (!effectiveOrganizationId) return;

    // Capture org id in closure for tenant isolation in payload handler
    const currentOrgId = effectiveOrganizationId;

    // Use unique channel name per org to prevent any cross-tenant leakage from stale channels
    const campaignsChannel = supabase
      .channel(`campaigns-realtime-${currentOrgId}`)
      .on(
        'postgres_changes',
        {
          event: '*',
          schema: 'public',
          table: 'campaigns',
          filter: `organization_id=eq.${currentOrgId}`,
        },
        (payload) => {
          // Defense-in-depth: ignore any payload that doesn't belong to the current org
          const rowOrgId =
            (payload.new as { organization_id?: string } | null)?.organization_id ??
            (payload.old as { organization_id?: string } | null)?.organization_id;
          if (rowOrgId && rowOrgId !== currentOrgId) {
            console.warn('[Disparos] Ignoring cross-tenant realtime payload', { rowOrgId, currentOrgId });
            return;
          }

            if (payload.eventType === 'UPDATE') {
            const newCampaign = payload.new as Campaign;
            setAllCampaigns((prev) =>
              prev.map((c) => {
                if (c.id !== newCampaign.id) return c;

                const currentUpdatedAt = c.updated_at ? new Date(c.updated_at).getTime() : 0;
                const nextUpdatedAt = newCampaign.updated_at ? new Date(newCampaign.updated_at).getTime() : 0;

                if (nextUpdatedAt < currentUpdatedAt) {
                  return c;
                }

                return {
                  ...c,
                  ...newCampaign,
                  status: newCampaign.status as Campaign["status"]
                };
              })
            );
          } else if (payload.eventType === 'INSERT') {
            setAllCampaigns((prev) => {
              if (prev.some((c) => c.id === (payload.new as Campaign).id)) return prev;
              return [payload.new as Campaign, ...prev];
            });
          } else if (payload.eventType === 'DELETE') {
            setAllCampaigns((prev) => prev.filter((c) => c.id !== (payload.old as { id: string }).id));
          }
        }
      )
      .subscribe();

    return () => {
      supabase.removeChannel(campaignsChannel);
    };
  }, [effectiveOrganizationId]);

  // Hook que processa campanhas em loop contínuo no frontend
  // Garante que campanhas NUNCA parem enquanto a página estiver aberta
  const { startProcessing } = useCampaignProcessor({
    campaigns: campaigns.map(c => ({
      id: c.id,
      name: c.name,
      status: c.status,
      sent_count: c.sent_count,
      total_recipients: c.total_recipients,
      min_interval: c.min_interval,
      max_interval: c.max_interval
    })),
    onUpdate: fetchData,
    enabled: true
  });

  // Polling para atualizar dados a cada 5 segundos quando há campanhas rodando (fallback)
  useEffect(() => {
    const hasRunningCampaigns = campaigns.some(c => c.status === "running");
    if (!hasRunningCampaigns) return;

    const pollInterval = setInterval(() => {
      fetchData();
    }, 10000); // Increased to 10s since we have realtime now

    return () => clearInterval(pollInterval);
  }, [campaigns, fetchData]);


  // Get templates available for a specific channel
  const getTemplatesForChannel = (channelId: string) => {
    const approvedTemplateIds = channelTemplateRelations
      .filter(ct => ct.channel_id === channelId)
      .map(ct => ct.template_id);
    
    return templates.filter(t => approvedTemplateIds.includes(t.id));
  };

  // Get templates that are approved in ALL selected channels (for unified template)
  const getUnifiedTemplates = () => {
    if (selectedChannels.length === 0) return [];
    
    return templates.filter(template => {
      return selectedChannels.every(channelId => {
        return channelTemplateRelations.some(
          ct => ct.channel_id === channelId && ct.template_id === template.id
        );
      });
    });
  };

  // Dispatch flows whose template is approved in ALL selected channels
  const getUnifiedFlows = () => {
    if (selectedChannels.length === 0) return [];
    const unifiedTplIds = new Set(getUnifiedTemplates().map(t => t.id));
    return dispatchFlows.filter(f => f.template_id && unifiedTplIds.has(f.template_id));
  };

  // Dispatch flows whose template is approved in a specific channel
  const getFlowsForChannel = (channelId: string) => {
    const tplIds = new Set(getTemplatesForChannel(channelId).map(t => t.id));
    return dispatchFlows.filter(f => f.template_id && tplIds.has(f.template_id));
  };

  // Get manual variables for the selected template (variables without auto-mapping)
  const getManualVariablesForTemplate = (templateId: string): string[] => {
    const template = templates.find(t => t.id === templateId);
    if (!template || !template.variables) return [];
    
    return template.variables.filter(varName => {
      const mapping = template.variable_mappings?.[varName];
      // Variable is manual if no mapping or mapping is empty/null/undefined
      return !mapping || mapping === '' || mapping === 'manual';
    });
  };

  // Get current selected template's manual variables
  const currentManualVariables = formData.unifiedTemplate 
    ? getManualVariablesForTemplate(formData.unifiedTemplate) 
    : [];

  // Handle template selection - reset manual variables when template changes
  const handleTemplateChange = (templateId: string) => {
    setFormData({ ...formData, unifiedTemplate: templateId });
    // Reset manual variables for new template
    const manualVars = getManualVariablesForTemplate(templateId);
    const newManualValues: Record<string, string> = {};
    manualVars.forEach(v => {
      newManualValues[v] = '';
    });
    setManualVariables(newManualValues);
  };

  const toggleChannel = (channelId: string) => {
    setSelectedChannels(prev => {
      const newSelected = prev.includes(channelId) 
        ? prev.filter(id => id !== channelId)
        : [...prev, channelId];
      
      if (!newSelected.includes(channelId)) {
        setChannelTemplates(current => {
          const updated = { ...current };
          delete updated[channelId];
          return updated;
        });
        setChannelManualVariables(current => {
          const updated = { ...current };
          delete updated[channelId];
          return updated;
        });
      }
      
      // Reset unified template if it's no longer valid
      if (useUnifiedTemplate) {
        const validUnified = templates.filter(template => {
          return newSelected.every(chId => {
            return channelTemplateRelations.some(
              ct => ct.channel_id === chId && ct.template_id === template.id
            );
          });
        });
        if (!validUnified.find(t => t.id === formData.unifiedTemplate)) {
          setFormData(prev => ({ ...prev, unifiedTemplate: "" }));
        }
      }
      
      return newSelected;
    });
  };

  const selectAllChannels = () => {
    if (selectedChannels.length === channels.length) {
      setSelectedChannels([]);
      setChannelTemplates({});
      setFormData(prev => ({ ...prev, unifiedTemplate: "" }));
    } else {
      setSelectedChannels(channels.map(c => c.id));
    }
  };

  const setChannelTemplate = (channelId: string, templateId: string) => {
    setChannelTemplates(prev => ({
      ...prev,
      [channelId]: templateId
    }));
    // Initialize manual variables for this channel's template
    const manualVars = getManualVariablesForTemplate(templateId);
    if (manualVars.length > 0) {
      const initialValues: Record<string, string> = {};
      manualVars.forEach(v => { initialValues[v] = ''; });
      setChannelManualVariables(prev => ({
        ...prev,
        [channelId]: initialValues
      }));
    } else {
      setChannelManualVariables(prev => {
        const updated = { ...prev };
        delete updated[channelId];
        return updated;
      });
    }
  };

  const getSelectedTemplatesPreview = () => {
    if (useUnifiedTemplate && formData.unifiedTemplate) {
      const template = templates.find(t => t.id === formData.unifiedTemplate);
      return template ? [template] : [];
    }
    
    const previewTemplates: MessageTemplate[] = [];
    selectedChannels.forEach(chId => {
      const templateId = channelTemplates[chId];
      if (templateId) {
        const template = templates.find(t => t.id === templateId);
        if (template && !previewTemplates.find(t => t.id === template.id)) {
          previewTemplates.push(template);
        }
      }
    });
    return previewTemplates;
  };

  const handleCreateCampaign = async () => {
    // Prevent double clicks
    if (isCreating) return;
    
    if (!formData.campaignName || selectedChannels.length === 0) {
      toast.error("Preencha o nome da campanha e selecione pelo menos um canal");
      return;
    }

    if (recipientData.phones.length === 0) {
      toast.error("Selecione os destinatários da campanha");
      return;
    }

    if (useUnifiedTemplate && !formData.unifiedTemplate) {
      toast.error("Selecione um template");
      return;
    }

    // Check if all manual variables are filled
    if (useUnifiedTemplate && currentManualVariables.length > 0) {
      const emptyVars = currentManualVariables.filter(v => !manualVariables[v]?.trim());
      if (emptyVars.length > 0) {
        toast.error(`Preencha todas as variáveis: ${emptyVars.join(', ')}`);
        return;
      }
    }

    if (templateMode === 'template_per_channel') {
      const allHaveTemplates = selectedChannels.every(chId => channelTemplates[chId]);
      if (!allHaveTemplates) {
        toast.error("Selecione um template para cada canal");
        return;
      }
      // Validate per-channel manual variables
      for (const chId of selectedChannels) {
        const templateId = channelTemplates[chId];
        if (!templateId) continue;
        const manualVars = getManualVariablesForTemplate(templateId);
        const channelVars = channelManualVariables[chId] || {};
        const emptyVars = manualVars.filter(v => !channelVars[v]?.trim());
        if (emptyVars.length > 0) {
          const channel = channels.find(c => c.id === chId);
          toast.error(`Preencha as variáveis do canal ${channel?.name}: ${emptyVars.join(', ')}`);
          return;
        }
      }
    }

    if (useFlowMode) {
      const unifiedFlows = getUnifiedFlows();
      const usingUnifiedFlow = unifiedFlows.length > 0 && selectedFlowId && unifiedFlows.some(f => f.id === selectedFlowId);
      if (!usingUnifiedFlow) {
        // require a flow per channel
        const allHaveFlows = selectedChannels.every(chId => channelFlows[chId]);
        if (!allHaveFlows) {
          toast.error(unifiedFlows.length > 0 ? "Selecione um flow para a campanha" : "Selecione um flow para cada canal");
          return;
        }
      }
    }

    // Validate scheduled date/time if scheduling
    if (formData.startTime === "scheduled") {
      if (!formData.scheduledDate || !formData.scheduledTime) {
        toast.error("Selecione a data e hora para o agendamento");
        return;
      }
      const scheduledDateTime = new Date(`${formData.scheduledDate}T${formData.scheduledTime}`);
      if (scheduledDateTime <= new Date()) {
        toast.error("A data/hora de agendamento deve ser no futuro");
        return;
      }
    }

    // Block the button immediately
    setIsCreating(true);

    try {
      // Pre-fetch ALL org leads ONCE (shared by "numbers" dedup + recipient name matching).
      // Paginated + parallelized via fetchAllLeads to bypass the 1000-row default limit.
      const orgLeadsAll = await fetchAllLeads<{ id: string; phone: string; name: string }>({
        organizationId: effectiveOrganizationId!,
        columns: "id, phone, name",
        orderBy: null,
      });

      // If source is "numbers", create leads for phones that don't exist in CRM
      if (recipientData.source === "numbers") {
        const orgLeads = orgLeadsAll;

        // Build a map of phone suffixes (last 8 digits) to lead data for flexible matching
        const leadsBySuffix = new Map<string, { phone: string; name: string }>();
        orgLeads?.forEach(lead => {
          const digits = lead.phone.replace(/\D/g, '');
          const suffix8 = digits.slice(-8);
          const suffix9 = digits.slice(-9);
          // Prefer leads with real names over auto-generated
          const isAutoGenerated = lead.name?.startsWith('LeadWhats-') || lead.name?.startsWith('WhatsApp ');
          const existing8 = leadsBySuffix.get(suffix8);
          const existing9 = leadsBySuffix.get(suffix9);
          if (!existing8 || (isAutoGenerated === false && (existing8.name.startsWith('LeadWhats-') || existing8.name.startsWith('WhatsApp ')))) {
            leadsBySuffix.set(suffix8, { phone: lead.phone, name: lead.name });
          }
          if (!existing9 || (isAutoGenerated === false && (existing9.name.startsWith('LeadWhats-') || existing9.name.startsWith('WhatsApp ')))) {
            leadsBySuffix.set(suffix9, { phone: lead.phone, name: lead.name });
          }
        });

        // Check which campaign phones already exist (by suffix match)
        const newPhones: string[] = [];
        recipientData.phones.forEach(phone => {
          const digits = phone.replace(/\D/g, '');
          const suffix8 = digits.slice(-8);
          const suffix9 = digits.slice(-9);
          const match = leadsBySuffix.get(suffix9) || leadsBySuffix.get(suffix8);
          if (!match) {
            newPhones.push(phone);
          }
        });

        if (newPhones.length > 0) {
          // Get the current count for naming
          const { count } = await supabase
            .from("leads")
            .select("*", { count: "exact", head: true })
            .ilike("name", "LeadWhats-%");

          const startIndex = (count || 0) + 1;

          const newLeads = newPhones.map((phone, idx) => ({
            user_id: user?.id,
            name: `LeadWhats-${String(startIndex + idx).padStart(5, "0")}`,
            phone: phone,
            organization_id: effectiveOrganizationId,
            status: "new"
          }));

          const { error: leadsError } = await supabase
            .from("leads")
            .insert(newLeads);

          if (leadsError) {
            console.error("Error creating leads:", leadsError);
            toast.warning("Alguns contatos podem não ter sido salvos");
          }
        }
      }

      // Determine chatbot_id based on selection
      const chatbotId = formData.chatbot === "enabled" && formData.chatbotSource === "custom" 
        ? formData.selectedChatbotId || null 
        : null;

      // Create campaign with min/max intervals and sector_id
      const sectorId = formData.department && formData.department !== "none" ? formData.department : null;
      
      // Calculate scheduled_at if scheduling for later
      const scheduledAt = formData.startTime === "scheduled" && formData.scheduledDate && formData.scheduledTime
        ? new Date(`${formData.scheduledDate}T${formData.scheduledTime}`).toISOString()
        : null;
      
      // Resolve flow-mode → effective template/flow ids per channel
      let effectiveUseUnified = useUnifiedTemplate;
      let effectiveUnifiedTemplateId: string | null = useUnifiedTemplate ? formData.unifiedTemplate : null;
      let effectiveUnifiedFlowId: string | null = null;
      const effectiveChannelTemplateMap: Record<string, string> = { ...channelTemplates };
      const effectiveChannelFlowMap: Record<string, string | null> = {};

      if (useFlowMode) {
        const unifiedFlows = getUnifiedFlows();
        const usingUnifiedFlow = !!selectedFlowId && unifiedFlows.some(f => f.id === selectedFlowId);
        if (usingUnifiedFlow) {
          const flow = unifiedFlows.find(f => f.id === selectedFlowId)!;
          effectiveUseUnified = true;
          effectiveUnifiedTemplateId = flow.template_id;
          effectiveUnifiedFlowId = flow.id;
          selectedChannels.forEach(chId => { effectiveChannelFlowMap[chId] = flow.id; });
        } else {
          effectiveUseUnified = false;
          effectiveUnifiedTemplateId = null;
          selectedChannels.forEach(chId => {
            const flowId = channelFlows[chId];
            const flow = dispatchFlows.find(f => f.id === flowId);
            if (flow?.template_id) {
              effectiveChannelTemplateMap[chId] = flow.template_id;
              effectiveChannelFlowMap[chId] = flow.id;
            }
          });
        }
      }

      const { data: campaign, error: campaignError } = await supabase
        .from("campaigns")
        .insert({
          user_id: user?.id,
          organization_id: effectiveOrganizationId,
          name: formData.campaignName,
          sector_id: sectorId,
          chatbot_enabled: formData.chatbot === "enabled",
          chatbot_id: chatbotId,
          dispatch_interval: parseInt(formData.minInterval),
          min_interval: parseInt(formData.minInterval),
          max_interval: parseInt(formData.maxInterval),
          use_unified_template: effectiveUseUnified,
          unified_template_id: effectiveUseUnified ? effectiveUnifiedTemplateId : null,
          flow_bot_id: effectiveUnifiedFlowId,
          status: formData.startTime === "now" ? "running" : "scheduled",
          scheduled_at: scheduledAt,
          total_recipients: recipientData.phones.length,
          // CRITICAL: Save manual variables for template substitution in batch processor
          // For per-channel mode, merge all channel variables (if same var name across channels, last wins)
          manual_variables: useUnifiedTemplate 
            ? (Object.keys(manualVariables).length > 0 ? manualVariables : null)
            : (() => {
                const merged: Record<string, string> = {};
                Object.values(channelManualVariables).forEach(vars => {
                  Object.entries(vars).forEach(([k, v]) => { if (v) merged[k] = v; });
                });
                return Object.keys(merged).length > 0 ? merged : null;
              })(),
        })
        .select()
        .single();

      if (campaignError) {
        toast.error("Erro ao criar campanha");
        console.error("Campaign creation error:", campaignError);
        setIsCreating(false);
        return;
      }

      // Create campaign channels
      const channelInserts = selectedChannels.map((channelId, index) => ({
        campaign_id: campaign.id,
        channel_id: channelId,
        template_id: effectiveUseUnified ? effectiveUnifiedTemplateId : effectiveChannelTemplateMap[channelId],
        flow_bot_id: effectiveChannelFlowMap[channelId] ?? null,
        order_index: index,
      }));

      const { error: channelsError } = await supabase
        .from("campaign_channels")
        .insert(channelInserts);

      if (channelsError) {
        toast.error("Erro ao salvar canais da campanha");
        setIsCreating(false);
        return;
      }

      // CRITICAL: Save campaign recipients BEFORE starting the campaign
      // IMPORTANT: Remove duplicate phone numbers to prevent sending multiple times
      const uniquePhones = [...new Set(recipientData.phones)];
      const duplicatesRemoved = recipientData.phones.length - uniquePhones.length;
      
      if (duplicatesRemoved > 0) {
        console.log(`[Campaign] Removed ${duplicatesRemoved} duplicate phone numbers`);
      }
      
      // Reuse the org leads pre-fetched at the top (no second roundtrip).
      const allOrgLeads = orgLeadsAll;

      // Build a flexible phone lookup map, prioritizing real names over auto-generated ones
      const leadMatches = new Map<string, LeadMatch>();
      allOrgLeads?.forEach(lead => {
        const candidate: LeadMatch = {
          id: lead.id,
          name: lead.name ?? null,
          isAutoGenerated: isAutoGeneratedLeadName(lead.name),
        };

        getPhoneLookupKeys(lead.phone).forEach((key) => {
          const current = leadMatches.get(key);
          leadMatches.set(key, chooseBetterLeadMatch(current, candidate));
        });
      });
      
      const recipientInserts = uniquePhones.map((phone) => {
        let matchedLead: LeadMatch | undefined;

        getPhoneLookupKeys(phone).forEach((key) => {
          const candidate = leadMatches.get(key);
          if (candidate) {
            matchedLead = chooseBetterLeadMatch(matchedLead, candidate);
          }
        });

        return {
          campaign_id: campaign.id,
          phone: phone,
          name: matchedLead?.name && !matchedLead.isAutoGenerated ? matchedLead.name : null,
          lead_id: matchedLead?.id ?? null,
          status: 'pending'
        };
      });
      
      // Update total recipients with the deduplicated count
      if (duplicatesRemoved > 0) {
        await supabase
          .from("campaigns")
          .update({ total_recipients: uniquePhones.length })
          .eq("id", campaign.id);
      }

      // Insert in batches of 500 to avoid hitting limits
      // Insert in batches of 500, with up to 5 batches in PARALLEL to drastically
      // reduce wait time for large campaigns (5k recipients: 10 batches → 2 waves).
      const batchSize = 500;
      const concurrency = 5;
      const batches: typeof recipientInserts[] = [];
      for (let i = 0; i < recipientInserts.length; i += batchSize) {
        batches.push(recipientInserts.slice(i, i + batchSize));
      }

      let cursor = 0;
      let failed = false;
      const workers = Array.from({ length: Math.min(concurrency, batches.length) }, async () => {
        while (cursor < batches.length && !failed) {
          const idx = cursor++;
          const { error: recipientError } = await supabase
            .from("campaign_recipients")
            .insert(batches[idx]);
          if (recipientError) {
            console.error("Error saving campaign recipients batch:", recipientError);
            failed = true;
            return;
          }
        }
      });
      await Promise.all(workers);

      if (failed) {
        toast.error("Erro ao salvar destinatários da campanha");
        await supabase.from("campaigns").update({ status: "failed" }).eq("id", campaign.id);
        setIsCreating(false);
        return;
      }

      console.log(`Successfully saved ${recipientInserts.length} recipients for campaign ${campaign.id}`);

      // Close form and reset immediately to prevent double clicks
      setShowCreateForm(false);
      resetForm();

      // If starting now, trigger the campaign dispatch (in background)
      if (formData.startTime === "now") {
        const duplicateMsg = duplicatesRemoved > 0 ? ` (${duplicatesRemoved} duplicados removidos)` : '';
        toast.success(`Campanha iniciada! Enviando para ${uniquePhones.length} destinatários${duplicateMsg}...`);
        
        // Don't await - let it run in background
        // Use unique phones only to ensure no duplicates are sent
        supabase.functions.invoke('campaign-dispatch', {
          body: { 
            campaignId: campaign.id, 
            action: 'start',
            recipients: uniquePhones,
            manualVariables: Object.keys(manualVariables).length > 0 ? manualVariables : undefined
          }
        }).then(response => {
          if (response.error) {
            console.error("Dispatch error:", response.error);
          }
        }).catch(dispatchError => {
          console.error("Error triggering dispatch:", dispatchError);
        });
      } else {
        const duplicateMsg = duplicatesRemoved > 0 ? ` (${duplicatesRemoved} duplicados removidos)` : '';
        toast.success(`Campanha agendada com sucesso!${duplicateMsg}`);
      }

      // Refresh data
      fetchData();
    } catch (error) {
      console.error("Error creating campaign:", error);
      toast.error("Erro ao criar campanha");
    } finally {
      setIsCreating(false);
    }
  };

  const resetForm = () => {
    setSelectedChannels([]);
    setChannelTemplates({});
    setTemplateMode('template_unified');
    setSelectedFlowId("");
    setChannelFlows({});
    setRecipientData({ phones: [], source: null });
    setManualVariables({});
    setChannelManualVariables({});
    setFormData({
      campaignName: "",
      department: "",
      chatbot: "disabled",
      chatbotSource: "channel",
      selectedChatbotId: "",
      startTime: "now",
      scheduledDate: "",
      scheduledTime: "",
      unifiedTemplate: "",
      cadenceType: "standard",
      minInterval: "5",
      maxInterval: "90"
    });
  };

  const [deleteCampaignId, setDeleteCampaignId] = useState<string | null>(null);
  const [deleteCampaignName, setDeleteCampaignName] = useState<string>("");

  const confirmDeleteCampaign = async () => {
    if (!deleteCampaignId) return;
    const { error } = await supabase.from("campaigns").delete().eq("id", deleteCampaignId);
    if (error) {
      toast.error("Erro ao excluir campanha");
      return;
    }
    toast.success("Campanha excluída");
    setDeleteCampaignId(null);
    fetchData();
  };

  const handleResumeCampaign = async (campaign: Campaign) => {
    try {
      // Update status to running AND acknowledge quality risk so webhook won't re-pause
      const { error: updateError } = await supabase
        .from("campaigns")
        .update({ 
          status: "running", 
          quality_pause_acknowledged: true,
          updated_at: new Date().toISOString() 
        })
        .eq("id", campaign.id);

      if (updateError) {
        toast.error("Erro ao retomar campanha");
        return;
      }

      toast.warning("Campanha retomada! Se foi pausada automaticamente por sinalização de qualidade, a responsabilidade é sua. Monitore os indicadores do número.", { duration: 8000 });
      
      // Refresh data to trigger the campaign processor hook
      fetchData();
      
      // Also manually start processing for immediate feedback
      startProcessing(campaign.id);
    } catch (error) {
      console.error("Error resuming campaign:", error);
      toast.error("Erro ao retomar campanha");
    }
  };

  const handlePauseCampaign = async (campaignId: string) => {
    try {
      const { error } = await supabase
        .from("campaigns")
        .update({ status: "paused" })
        .eq("id", campaignId);

      if (error) {
        toast.error("Erro ao pausar campanha");
        return;
      }

      toast.success("Campanha pausada");
      fetchData();
    } catch (error) {
      console.error("Error pausing campaign:", error);
      toast.error("Erro ao pausar campanha");
    }
  };

  const handleForceSyncCampaign = async (campaignId: string) => {
    try {
      toast.info("Sincronizando status de entrega...");

      // 1. Re-subscribe webhooks for all channels of this campaign
      const { data: campaignChannelsData } = await supabase
        .from("campaign_channels")
        .select("channel_id")
        .eq("campaign_id", campaignId);

      if (campaignChannelsData) {
        const channelIds = campaignChannelsData.map(cc => cc.channel_id);
        const { data: channelsList } = await supabase
          .from("channels")
          .select("id, app_name, access_token, waba_id, provider")
          .in("id", channelIds)
          .eq("provider", "meta");

        if (channelsList) {
          await Promise.all(channelsList.map(ch =>
            supabase.functions.invoke("meta-subscribe-webhook", {
              body: {
                phoneNumberId: ch.app_name,
                accessToken: ch.access_token,
                wabaId: ch.waba_id,
              }
            })
          ));
        }
      }

      // 2. Force sync campaign counts from campaign_recipients
      await supabase.rpc("force_sync_all_campaign_counts");

      toast.success("Sincronização concluída! Webhooks re-inscritos.");
      fetchData();
    } catch (error) {
      console.error("Error syncing campaign:", error);
      toast.error("Erro ao sincronizar campanha");
    }
  };

  const handleViewDetails = async (campaignId: string) => {
    // Try to find in local state first
    let campaign = campaigns.find(c => c.id === campaignId);
    
    // If not found (e.g., from progress bar), fetch from database
    if (!campaign) {
      const { data } = await supabase
        .from("campaigns")
        .select("*")
        .eq("id", campaignId)
        .single();
      
      if (data) {
        campaign = {
          ...data,
          status: data.status as Campaign["status"]
        };
      }
    }
    
    if (campaign) {
      setSelectedCampaign(campaign);
      setShowReportDialog(true);
    }
  };

  const handleRecycleCampaign = (campaign: Campaign) => {
    setRecyclingCampaign(campaign);
    setShowRecycleDialog(true);
  };

  const stats = {
    total: campaigns.length,
    running: campaigns.filter(c => c.status === "running").length,
    sent: campaigns.reduce((acc, c) => acc + c.sent_count, 0),
    deliveryRate: campaigns.reduce((acc, c) => acc + c.sent_count, 0) > 0
      ? Math.round((campaigns.reduce((acc, c) => acc + c.delivered_count, 0) / 
          campaigns.reduce((acc, c) => acc + c.sent_count, 0)) * 100)
      : 0,
  };

  if (showCreateForm) {
    const unifiedTemplates = getUnifiedTemplates();

    return (
      <MainLayout>
        {/* Header */}
        <div className="mb-6 animate-fade-in">
          <Button 
            variant="ghost" 
            className="gap-2 mb-4 text-muted-foreground hover:text-foreground"
            onClick={() => { setShowCreateForm(false); resetForm(); }}
          >
            <ArrowLeft className="w-4 h-4" />
            Voltar
          </Button>
          <h1 className="text-2xl font-bold text-foreground mb-2">Configuração de campanha</h1>
          <p className="text-muted-foreground text-sm">
            Crie campanhas para engajar seus clientes. Selecione canais e templates aprovados.
          </p>
        </div>

        {channels.length === 0 ? (
          <div className="text-center py-12 bg-card rounded-lg border border-border">
            <Smartphone className="w-12 h-12 text-muted-foreground/50 mx-auto mb-4" />
            <p className="text-muted-foreground">Nenhum canal conectado</p>
            <p className="text-sm text-muted-foreground/70 mt-1">
              Conecte canais na página de Conexões para criar campanhas
            </p>
          </div>
        ) : (
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 animate-slide-up">
            {/* Left Column */}
            <div className="space-y-5">
              <div className="space-y-2">
                <Label className="text-foreground">
                  Nome da campanha <span className="text-destructive">*</span>
                </Label>
                <div className="flex items-center gap-2">
                  <Input 
                    placeholder="Digite o nome da campanha"
                    className="bg-card border-border"
                    value={formData.campaignName}
                    onChange={(e) => setFormData({ ...formData, campaignName: e.target.value })}
                  />
                  {formData.campaignName && <Check className="w-5 h-5 text-primary" />}
                </div>
              </div>

              <div className="space-y-2">
                <Label className="text-foreground">Departamento</Label>
                <Select 
                  value={formData.department} 
                  onValueChange={(value) => setFormData({ ...formData, department: value })}
                >
                  <SelectTrigger className="bg-card border-border">
                    <SelectValue placeholder="Selecione o departamento" />
                  </SelectTrigger>
                  <SelectContent className="bg-card border-border">
                    {sectors.length === 0 ? (
                      <SelectItem value="none" disabled>Nenhum departamento cadastrado</SelectItem>
                    ) : (
                      <>
                        <SelectItem value="none">Nenhum (opcional)</SelectItem>
                        {sectors.map((sector) => (
                          <SelectItem key={sector.id} value={sector.id}>
                            {sector.name}
                          </SelectItem>
                        ))}
                      </>
                    )}
                  </SelectContent>
                </Select>
              </div>

              {/* Channel Selection */}
              <ChannelSelectionByAccount
                channels={channels}
                selectedChannels={selectedChannels}
                toggleChannel={toggleChannel}
                setSelectedChannels={setSelectedChannels}
                setChannelTemplates={setChannelTemplates}
                setFormData={setFormData}
              />
              {selectedChannels.length > 0 && (
                <div className="flex items-center gap-2 text-xs text-primary">
                  <Check className="w-4 h-4" />
                  <span>{selectedChannels.length} canal(is) selecionado(s)</span>
                </div>
              )}

              {/* Recipient Selection */}
              <div className="space-y-3">
                <RecipientSelection 
                  onSelectionChange={setRecipientData} 
                  sectorId={formData.department && formData.department !== "none" ? formData.department : undefined}
                />
              </div>

              {/* Random Cadence Dispatch */}
              <div className="space-y-4 p-4 bg-primary/5 rounded-lg border border-primary/20">
                <div className="flex items-center gap-2">
                  <Shuffle className="w-5 h-5 text-primary" />
                  <Label className="text-foreground font-medium">Cadência de Disparo</Label>
                </div>
                <p className="text-xs text-muted-foreground">
                  Escolha o tipo de cadência para os disparos. A cadência de aquecimento é mais lenta e recomendada para números novos.
                </p>
                
                <div className={`grid gap-3 ${role === "super_admin" ? "grid-cols-3" : "grid-cols-2"}`}>
                  <div 
                    className={`p-4 rounded-lg border-2 cursor-pointer transition-all ${
                      formData.cadenceType === "standard" 
                        ? "border-primary bg-primary/10" 
                        : "border-border bg-card hover:border-primary/50"
                    }`}
                    onClick={() => setFormData({ 
                      ...formData, 
                      cadenceType: "standard",
                      minInterval: "5",
                      maxInterval: "90"
                    })}
                  >
                    <div className="flex items-center gap-2 mb-2">
                      <div className={`w-4 h-4 rounded-full border-2 flex items-center justify-center ${
                        formData.cadenceType === "standard" ? "border-primary" : "border-muted-foreground"
                      }`}>
                        {formData.cadenceType === "standard" && (
                          <div className="w-2 h-2 rounded-full bg-primary" />
                        )}
                      </div>
                      <span className="font-medium text-foreground">Padrão</span>
                    </div>
                    <p className="text-xs text-muted-foreground">
                      Intervalos de <strong>5 seg</strong> a <strong>1 min 30 seg</strong>
                    </p>
                    <p className="text-xs text-primary mt-1">Recomendado para números já aquecidos</p>
                  </div>
                  
                  <div 
                    className={`p-4 rounded-lg border-2 cursor-pointer transition-all ${
                      formData.cadenceType === "warmup" 
                        ? "border-primary bg-primary/10" 
                        : "border-border bg-card hover:border-primary/50"
                    }`}
                    onClick={() => setFormData({ 
                      ...formData, 
                      cadenceType: "warmup",
                      minInterval: "180",
                      maxInterval: "300"
                    })}
                  >
                    <div className="flex items-center gap-2 mb-2">
                      <div className={`w-4 h-4 rounded-full border-2 flex items-center justify-center ${
                        formData.cadenceType === "warmup" ? "border-primary" : "border-muted-foreground"
                      }`}>
                        {formData.cadenceType === "warmup" && (
                          <div className="w-2 h-2 rounded-full bg-primary" />
                        )}
                      </div>
                      <span className="font-medium text-foreground">Aquecimento</span>
                    </div>
                    <p className="text-xs text-muted-foreground">
                      Intervalos de <strong>3 min</strong> a <strong>5 min</strong>
                    </p>
                    <p className="text-xs text-amber-500 mt-1">Para números novos ou pouco usados</p>
                  </div>

                  {role === "super_admin" && (
                    <div 
                      className={`p-4 rounded-lg border-2 cursor-pointer transition-all ${
                        formData.cadenceType === "full" 
                          ? "border-destructive bg-destructive/10" 
                          : "border-border bg-card hover:border-destructive/50"
                      }`}
                      onClick={() => setFormData({ 
                        ...formData, 
                        cadenceType: "full",
                        minInterval: "0",
                        maxInterval: "0"
                      })}
                    >
                      <div className="flex items-center gap-2 mb-2">
                        <div className={`w-4 h-4 rounded-full border-2 flex items-center justify-center ${
                          formData.cadenceType === "full" ? "border-destructive" : "border-muted-foreground"
                        }`}>
                          {formData.cadenceType === "full" && (
                            <div className="w-2 h-2 rounded-full bg-destructive" />
                          )}
                        </div>
                        <span className="font-medium text-foreground">Full</span>
                      </div>
                      <p className="text-xs text-muted-foreground">
                        <strong>Sem intervalo</strong> — todos de uma vez
                      </p>
                      <p className="text-xs text-destructive mt-1">Apenas para administradores</p>
                    </div>
                  )}
                </div>

                <div className="flex items-center gap-2 p-3 bg-primary/10 rounded-lg">
                  <Timer className="w-4 h-4 text-primary" />
                  <p className="text-xs text-primary">
                    {formData.cadenceType === "standard" 
                      ? "Disparos rápidos com intervalos entre 5 segundos e 1 minuto e 30 segundos"
                      : formData.cadenceType === "warmup"
                        ? "Disparos lentos com intervalos entre 3 e 5 minutos para aquecer o número"
                        : "⚡ Disparo FULL — todas as mensagens serão enviadas simultaneamente, sem intervalo"
                    }
                  </p>
                </div>

                {selectedChannels.length > 1 && (
                  <p className="text-xs text-muted-foreground border-t border-border/50 pt-3 mt-2">
                    As mensagens também serão alternadas entre os {selectedChannels.length} canais selecionados.
                  </p>
                )}
              </div>

              <div className="space-y-3">
                <Label className="text-foreground">Habilitar chatbot</Label>
                <Select 
                  value={formData.chatbot} 
                  onValueChange={(value) => setFormData({ ...formData, chatbot: value, chatbotSource: "channel", selectedChatbotId: "" })}
                >
                  <SelectTrigger className="bg-card border-border">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent className="bg-card border-border">
                    <SelectItem value="disabled">Desabilitado</SelectItem>
                    <SelectItem value="enabled">Habilitado</SelectItem>
                  </SelectContent>
                </Select>

                {formData.chatbot === "enabled" && (
                  <div className="space-y-3 p-3 bg-primary/5 rounded-lg border border-primary/20">
                    <div className="flex items-center gap-2 text-sm text-primary">
                      <Bot className="w-4 h-4" />
                      <span className="font-medium">Configuração do Chatbot</span>
                    </div>
                    
                    <div className="flex gap-2">
                      <Button
                        variant={formData.chatbotSource === "channel" ? "default" : "outline"}
                        size="sm"
                        className="flex-1"
                        onClick={() => setFormData({ ...formData, chatbotSource: "channel", selectedChatbotId: "" })}
                      >
                        Usar do canal
                      </Button>
                      <Button
                        variant={formData.chatbotSource === "custom" ? "default" : "outline"}
                        size="sm"
                        className="flex-1"
                        onClick={() => setFormData({ ...formData, chatbotSource: "custom" })}
                      >
                        Escolher outro
                      </Button>
                    </div>

                    {formData.chatbotSource === "channel" ? (
                      <p className="text-xs text-muted-foreground">
                        O chatbot configurado em cada canal será usado automaticamente.
                      </p>
                    ) : (
                      <div className="space-y-2">
                        <Select 
                          value={formData.selectedChatbotId} 
                          onValueChange={(value) => setFormData({ ...formData, selectedChatbotId: value })}
                        >
                          <SelectTrigger className="bg-card border-border">
                            <SelectValue placeholder="Selecione o chatbot" />
                          </SelectTrigger>
                          <SelectContent className="bg-card border-border">
                            {aiAgents.length === 0 ? (
                              <div className="p-3 text-center text-muted-foreground text-sm">
                                Nenhum chatbot configurado
                              </div>
                            ) : (
                              aiAgents.map(agent => (
                                <SelectItem key={agent.id} value={agent.id}>
                                  {agent.name}
                                </SelectItem>
                              ))
                            )}
                          </SelectContent>
                        </Select>
                        <p className="text-xs text-muted-foreground">
                          Este chatbot será usado para todos os contatos desta campanha, independente da configuração do canal.
                        </p>
                      </div>
                    )}
                  </div>
                )}
              </div>

              <div className="space-y-2">
                <Label className="text-foreground">Início do disparo</Label>
                <Select 
                  value={formData.startTime} 
                  onValueChange={(value) => setFormData({ ...formData, startTime: value })}
                >
                  <SelectTrigger className="bg-card border-border">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent className="bg-card border-border">
                    <SelectItem value="now">Iniciar agora</SelectItem>
                    <SelectItem value="scheduled">Agendar para depois</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              {formData.startTime === "scheduled" && (
                <div className="space-y-3 p-3 bg-warning/10 rounded-lg border border-warning/30">
                  <div className="flex items-center gap-2 text-sm text-warning">
                    <Calendar className="w-4 h-4" />
                    <span className="font-medium">Agendamento do disparo</span>
                  </div>
                  <div className="grid grid-cols-2 gap-3">
                    <div className="space-y-1">
                      <Label className="text-xs text-muted-foreground">Data</Label>
                      <Input
                        type="date"
                        value={formData.scheduledDate}
                        min={new Date().toISOString().split('T')[0]}
                        onChange={(e) => setFormData({ ...formData, scheduledDate: e.target.value })}
                        className="bg-card border-border"
                      />
                    </div>
                    <div className="space-y-1">
                      <Label className="text-xs text-muted-foreground">Horário</Label>
                      <Input
                        type="time"
                        value={formData.scheduledTime}
                        onChange={(e) => setFormData({ ...formData, scheduledTime: e.target.value })}
                        className="bg-card border-border"
                      />
                    </div>
                  </div>
                  {formData.scheduledDate && formData.scheduledTime && (
                    <p className="text-xs text-warning">
                      📅 Disparo programado para {new Date(`${formData.scheduledDate}T${formData.scheduledTime}`).toLocaleString('pt-BR')}
                    </p>
                  )}
                </div>
              )}

              {/* Summary */}
              <div className="pt-4 border-t border-border space-y-2">
                <div className="flex justify-between text-sm">
                  <span className="text-primary font-medium">Canais selecionados:</span>
                  <span className="text-foreground">{selectedChannels.length}</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-primary font-medium">Destinatários:</span>
                  <span className="text-foreground">
                    {recipientData.phones.length > 0 
                      ? `${recipientData.phones.length} (${recipientData.source === "contacts" ? "contatos" : "números"})`
                      : "Nenhum selecionado"
                    }
                  </span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-primary font-medium">Cadência:</span>
                  <span className="text-foreground flex items-center gap-1">
                    <Shuffle className="w-3 h-3" />
                    {formData.cadenceType === "full" 
                      ? "Full (sem intervalo)" 
                      : `${formData.minInterval}s - ${formData.maxInterval}s (aleatório)`
                    }
                  </span>
                </div>
              </div>
            </div>

            {/* Right Column - Templates */}
            <div className="space-y-5">
              <div className="space-y-3">
                <Label className="text-foreground">
                  Templates de Mensagem <span className="text-destructive">*</span>
                </Label>
                
                <div className="flex gap-2">
                  <Button
                    variant={useUnifiedTemplate ? "default" : "outline"}
                    size="sm"
                    className="flex-1"
                    onClick={() => setUseUnifiedTemplate(true)}
                  >
                    Mesmo template
                  </Button>
                  <Button
                    variant={!useUnifiedTemplate ? "default" : "outline"}
                    size="sm"
                    className="flex-1"
                    onClick={() => setUseUnifiedTemplate(false)}
                  >
                    Template por canal
                  </Button>
                </div>
              </div>

              {useUnifiedTemplate ? (
                <div className="space-y-3">
                  <Select 
                    value={formData.unifiedTemplate} 
                    onValueChange={handleTemplateChange}
                  >
                    <SelectTrigger className="bg-card border-border">
                      <SelectValue placeholder="Selecione o template" />
                    </SelectTrigger>
                    <SelectContent className="bg-card border-border">
                      {unifiedTemplates.length === 0 ? (
                        <div className="p-3 text-center text-muted-foreground text-sm">
                          {selectedChannels.length === 0 
                            ? "Selecione canais primeiro"
                            : "Nenhum template aprovado em todos os canais"}
                        </div>
                      ) : (
                        unifiedTemplates.map(template => (
                          <SelectItem key={template.id} value={template.id}>
                            <div className="flex items-center gap-2">
                              <span>{template.name}</span>
                              {template.dispatch_type && (
                                <span className={`text-[10px] px-1.5 py-0.5 rounded-full border ${
                                  template.dispatch_type === 'marketing' 
                                    ? 'bg-purple-500/10 text-purple-500 border-purple-500/30' 
                                    : template.dispatch_type === 'utility'
                                    ? 'bg-blue-500/10 text-blue-500 border-blue-500/30'
                                    : 'bg-green-500/10 text-green-500 border-green-500/30'
                                }`}>
                                  {template.dispatch_type === 'marketing' ? 'Marketing' : 
                                   template.dispatch_type === 'utility' ? 'Utilitário' : 'Serviço'}
                                </span>
                              )}
                              {template.variables && template.variables.length > 0 && (
                                <span className="text-muted-foreground text-xs">
                                  ({template.variables.length} var.)
                                </span>
                              )}
                            </div>
                          </SelectItem>
                        ))
                      )}
                    </SelectContent>
                  </Select>
                  <p className="text-xs text-muted-foreground">
                    Apenas templates aprovados em todos os canais selecionados são exibidos.
                  </p>

                  {/* Manual Variables Input */}
                  {currentManualVariables.length > 0 && formData.unifiedTemplate && (
                    <div className="p-4 bg-warning/10 border border-warning/30 rounded-lg space-y-3">
                      <div className="flex items-center gap-2 text-warning">
                        <Settings2 className="w-4 h-4" />
                        <span className="font-medium text-sm">Variáveis a informar</span>
                      </div>
                      <p className="text-xs text-muted-foreground">
                        Este template possui variáveis que precisam ser preenchidas manualmente. 
                        O mesmo valor será usado para todos os destinatários.
                      </p>
                      <div className="space-y-2">
                        {currentManualVariables.map((varName) => (
                          <div key={varName}>
                            <Label className="text-sm mb-1 block">{varName}</Label>
                            <Input
                              placeholder={`Valor para ${varName}`}
                              value={manualVariables[varName] || ''}
                              onChange={(e) => setManualVariables(prev => ({
                                ...prev,
                                [varName]: e.target.value
                              }))}
                              className="bg-card"
                            />
                          </div>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              ) : (
                <div className="space-y-3">
                  <p className="text-xs text-muted-foreground">
                    Selecione um template aprovado para cada canal.
                  </p>
                  
                  <div className="space-y-2 max-h-96 overflow-y-auto">
                    {selectedChannels.length === 0 ? (
                      <div className="text-center py-6 text-muted-foreground text-sm">
                        Selecione pelo menos um canal
                      </div>
                    ) : (
                      selectedChannels.map(chId => {
                        const channel = channels.find(c => c.id === chId);
                        const selectedTemplate = channelTemplates[chId];
                        const template = templates.find(t => t.id === selectedTemplate);
                        const availableTemplates = getTemplatesForChannel(chId);
                        
                        return (
                          <div 
                            key={chId}
                            className="p-3 bg-card rounded-lg border border-border space-y-2"
                          >
                            <div className="flex items-center gap-2">
                              <Smartphone className="w-4 h-4 text-primary" />
                              <span className="text-sm font-medium text-foreground flex-1">
                                {channel?.name}
                              </span>
                              {selectedTemplate && <Check className="w-4 h-4 text-primary" />}
                            </div>
                            <Select 
                              value={selectedTemplate || ""} 
                              onValueChange={(value) => setChannelTemplate(chId, value)}
                            >
                              <SelectTrigger className="bg-muted/50 border-border h-9">
                                <SelectValue placeholder="Selecione o template" />
                              </SelectTrigger>
                              <SelectContent className="bg-card border-border">
                                {availableTemplates.length === 0 ? (
                                  <div className="p-3 text-center text-muted-foreground text-sm">
                                    Nenhum template aprovado neste canal
                                  </div>
                                ) : (
                                  availableTemplates.map(t => (
                                    <SelectItem key={t.id} value={t.id}>
                                      <div className="flex items-center gap-2">
                                        <span>{t.name}</span>
                                        {t.dispatch_type && (
                                          <span className={`text-[10px] px-1.5 py-0.5 rounded-full border ${
                                            t.dispatch_type === 'marketing' 
                                              ? 'bg-purple-500/10 text-purple-500 border-purple-500/30' 
                                              : t.dispatch_type === 'utility'
                                              ? 'bg-blue-500/10 text-blue-500 border-blue-500/30'
                                              : 'bg-green-500/10 text-green-500 border-green-500/30'
                                          }`}>
                                            {t.dispatch_type === 'marketing' ? 'Marketing' : 
                                             t.dispatch_type === 'utility' ? 'Utilitário' : 'Serviço'}
                                          </span>
                                        )}
                                      </div>
                                    </SelectItem>
                                  ))
                                )}
                              </SelectContent>
                            </Select>
                            {template && (
                              <p className="text-xs text-muted-foreground truncate">
                                {template.content.substring(0, 80)}...
                              </p>
                            )}
                            {/* Per-channel manual variables */}
                            {(() => {
                              const templateId = channelTemplates[chId];
                              if (!templateId) return null;
                              const manualVars = getManualVariablesForTemplate(templateId);
                              if (manualVars.length === 0) return null;
                              const channelVars = channelManualVariables[chId] || {};
                              return (
                                <div className="p-3 bg-warning/10 border border-warning/30 rounded-lg space-y-2 mt-1">
                                  <div className="flex items-center gap-2 text-warning">
                                    <Settings2 className="w-3.5 h-3.5" />
                                    <span className="font-medium text-xs">Variáveis do template</span>
                                  </div>
                                  {manualVars.map((varName) => (
                                    <div key={varName}>
                                      <Label className="text-xs mb-1 block">{varName}</Label>
                                      <Input
                                        placeholder={`Valor para ${varName}`}
                                        value={channelVars[varName] || ''}
                                        onChange={(e) => setChannelManualVariables(prev => ({
                                          ...prev,
                                          [chId]: {
                                            ...(prev[chId] || {}),
                                            [varName]: e.target.value
                                          }
                                        }))}
                                        className="bg-card h-8 text-sm"
                                      />
                                    </div>
                                  ))}
                                </div>
                              );
                            })()}
                          </div>
                        );
                      })
                    )}
                  </div>
                </div>
              )}

              {/* Message Preview */}
              <div 
                className="rounded-lg border border-border overflow-hidden"
                style={{ 
                  background: 'linear-gradient(135deg, hsl(160 10% 15%), hsl(160 10% 12%))',
                  backgroundImage: `url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23ffffff' fill-opacity='0.03'%3E%3Cpath d='M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E")` 
                }}
              >
                <div className="p-3 border-b border-border/50 bg-card/30">
                  <p className="text-xs text-muted-foreground">Prévia das mensagens</p>
                </div>
                <div className="min-h-48 max-h-64 overflow-y-auto p-4 space-y-3">
                  {getSelectedTemplatesPreview().length > 0 ? (
                    getSelectedTemplatesPreview().map((template, idx) => (
                      <div key={template.id} className="bg-card rounded-lg p-3 max-w-[85%] shadow-lg">
                        <Badge variant="outline" className="text-xs mb-2 bg-primary/10 border-primary/30 text-primary">
                          {template.name}
                        </Badge>
                        <p className="text-foreground text-sm">
                          {template.content.substring(0, 150)}...
                        </p>
                        <span className="text-xs text-muted-foreground mt-2 block text-right">12:0{idx}</span>
                      </div>
                    ))
                  ) : (
                    <div className="h-full flex items-center justify-center py-12">
                      <p className="text-muted-foreground/50 text-sm text-center">
                        Selecione template(s) para visualizar
                      </p>
                    </div>
                  )}
                </div>
              </div>
            </div>
          </div>
        )}

        {/* Action Buttons */}
        {channels.length > 0 && (
          <div className="flex justify-end gap-3 mt-8 pt-6 border-t border-border">
            <Button 
              variant="outline" 
              onClick={() => { setShowCreateForm(false); resetForm(); }}
              disabled={isCreating}
            >
              Cancelar
            </Button>
            <Button 
              className="gap-2" 
              onClick={handleCreateCampaign}
              disabled={isCreating}
            >
              {isCreating ? (
                <>
                  <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                  Criando...
                </>
              ) : (
                <>
                  <Send className="w-4 h-4" />
                  Criar Campanha
                </>
              )}
            </Button>
          </div>
        )}
      </MainLayout>
    );
  }

  return (
    <MainLayout>
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8 animate-fade-in">
        <div>
          <h1 className="text-2xl font-bold text-foreground mb-1">Disparos</h1>
          <p className="text-muted-foreground">Gerencie suas campanhas de mensagens</p>
        </div>
        <div className="flex gap-2">
          <Button 
            variant="outline" 
            className="gap-2" 
            onClick={() => fetchData()}
            disabled={loading}
          >
            <RefreshCw className={cn("w-4 h-4", loading && "animate-spin")} />
            Atualizar
          </Button>
          <Button className="gap-2" onClick={() => setShowCreateForm(true)}>
            <Plus className="w-4 h-4" />
            Nova Campanha
          </Button>
        </div>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-8">
        <div className="bg-card rounded-lg border border-border p-5">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-muted-foreground">Total de Campanhas</p>
              <p className="text-2xl font-bold text-foreground">{stats.total}</p>
            </div>
            <Send className="w-6 h-6 text-primary" />
          </div>
        </div>
        <div className="bg-card rounded-lg border border-border p-5">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-muted-foreground">Em Execução</p>
              <p className="text-2xl font-bold text-blue-400">{stats.running}</p>
            </div>
            <Play className="w-6 h-6 text-blue-400" />
          </div>
        </div>
        <div className="bg-card rounded-lg border border-border p-5">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-muted-foreground">Mensagens Enviadas</p>
              <p className="text-2xl font-bold text-foreground">{stats.sent.toLocaleString()}</p>
            </div>
            <MessageSquare className="w-6 h-6 text-primary" />
          </div>
        </div>
        <div className="bg-card rounded-lg border border-border p-5">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-muted-foreground">Taxa de Entrega</p>
              <p className="text-2xl font-bold text-primary">{stats.deliveryRate}%</p>
            </div>
            <CheckCircle className="w-6 h-6 text-primary" />
          </div>
        </div>
      </div>

      {/* Real-time Progress Bar */}
      <CampaignProgressBar onViewDetails={handleViewDetails} />

      {/* Table */}
      <div className="bg-card rounded-lg border border-border overflow-hidden animate-slide-up">
        {loading ? (
          <div className="p-8 text-center text-muted-foreground">Carregando...</div>
        ) : campaigns.length === 0 ? (
          <div className="p-8 text-center">
            <Send className="w-12 h-12 text-muted-foreground/30 mx-auto mb-4" />
            <p className="text-muted-foreground">Nenhuma campanha criada</p>
            <Button className="mt-4" onClick={() => setShowCreateForm(true)}>
              Criar primeira campanha
            </Button>
          </div>
        ) : (
          <Table>
            <TableHeader>
              <TableRow className="border-border hover:bg-muted/30">
                <TableHead className="text-muted-foreground">Campanha</TableHead>
                <TableHead className="text-muted-foreground">Status</TableHead>
                <TableHead className="text-muted-foreground">Destinatários</TableHead>
                <TableHead className="text-muted-foreground">Enviadas</TableHead>
                <TableHead className="text-muted-foreground">Entregues</TableHead>
                <TableHead className="text-muted-foreground">Falhas</TableHead>
                <TableHead className="w-12"></TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {campaigns.map((campaign) => {
                const config = statusConfig[campaign.status];
                const StatusIcon = config.icon;

                // Detecta inconsistências entre os contadores e o total de destinatários
                const sent = campaign.sent_count || 0;
                const delivered = campaign.delivered_count || 0;
                const failed = campaign.failed_count || 0;
                const total = campaign.total_recipients || 0;
                const processed = sent + failed;
                const inconsistencies: string[] = [];
                if (delivered > sent) {
                  inconsistencies.push(`Entregues (${delivered}) > Enviadas (${sent})`);
                }
                if (total > 0 && processed > total) {
                  inconsistencies.push(`Processadas (${processed}) > Total (${total})`);
                }
                if (
                  total > 0 &&
                  ["completed", "paused"].includes(campaign.status) &&
                  processed < total
                ) {
                  inconsistencies.push(`Processadas (${processed}) < Total (${total})`);
                }
                const hasInconsistency = inconsistencies.length > 0;

                return (
                  <TableRow 
                    key={campaign.id}
                    className={cn(
                      "border-border hover:bg-muted/20 cursor-pointer",
                      hasInconsistency && "bg-amber-500/5"
                    )}
                    onClick={() => handleViewDetails(campaign.id)}
                  >
                    <TableCell>
                      <div className="flex items-center gap-2">
                        <div className="min-w-0">
                          <p className="font-medium text-foreground flex items-center gap-2">
                            {campaign.name}
                            {hasInconsistency && (
                              <TooltipProvider>
                                <Tooltip>
                                  <TooltipTrigger asChild>
                                    <span
                                      onClick={(e) => e.stopPropagation()}
                                      className="inline-flex items-center"
                                    >
                                      <AlertTriangle className="w-4 h-4 text-amber-500" />
                                    </span>
                                  </TooltipTrigger>
                                  <TooltipContent side="right" className="max-w-xs">
                                    <p className="font-semibold mb-1">Inconsistência detectada</p>
                                    <ul className="text-xs list-disc pl-4 space-y-0.5">
                                      {inconsistencies.map((msg, i) => (
                                        <li key={i}>{msg}</li>
                                      ))}
                                    </ul>
                                    <p className="text-xs mt-2 text-muted-foreground">
                                      Use "Forçar sincronização" para recalcular.
                                    </p>
                                  </TooltipContent>
                                </Tooltip>
                              </TooltipProvider>
                            )}
                          </p>
                          <p className="text-xs text-muted-foreground">
                            {campaign.scheduled_at 
                              ? `Agendada: ${new Date(campaign.scheduled_at).toLocaleDateString()}`
                              : `Criada: ${new Date(campaign.created_at).toLocaleDateString()}`}
                          </p>
                        </div>
                      </div>
                    </TableCell>
                    <TableCell>
                      <Badge variant="outline" className={cn("text-xs gap-1", config.className)}>
                        <StatusIcon className="w-3 h-3" />
                        {config.label}
                      </Badge>
                    </TableCell>
                    <TableCell>
                      <span className="text-foreground">{campaign.total_recipients}</span>
                    </TableCell>
                    <TableCell>
                      <span className={cn("text-foreground", hasInconsistency && "text-amber-600 font-medium")}>{campaign.sent_count}</span>
                    </TableCell>
                    <TableCell>
                      <span className={cn("text-primary", delivered > sent && "text-amber-600 font-medium")}>{campaign.delivered_count}</span>
                    </TableCell>
                    <TableCell>
                      <span className="text-destructive">{campaign.failed_count}</span>
                    </TableCell>
                    <TableCell onClick={(e) => e.stopPropagation()}>
                      <DropdownMenu>
                        <DropdownMenuTrigger asChild>
                          <Button variant="ghost" size="icon" className="h-8 w-8">
                            <MoreVertical className="w-4 h-4" />
                          </Button>
                        </DropdownMenuTrigger>
                        <DropdownMenuContent align="end" className="bg-card border-border">
                          <DropdownMenuItem onClick={() => handleViewDetails(campaign.id)}>
                            <Eye className="w-4 h-4 mr-2" />
                            Ver detalhes
                          </DropdownMenuItem>
                          <DropdownMenuItem>Duplicar</DropdownMenuItem>
                          {campaign.status === "completed" && campaign.failed_count > 0 && (
                            <DropdownMenuItem onClick={() => handleRecycleCampaign(campaign)}>
                              <RotateCcw className="w-4 h-4 mr-2" />
                              Reciclar falhas ({campaign.failed_count})
                            </DropdownMenuItem>
                          )}
                          {campaign.status === "running" && (
                            <>
                              <DropdownMenuItem onClick={() => handlePauseCampaign(campaign.id)}>
                                <Pause className="w-4 h-4 mr-2" />
                                Pausar
                              </DropdownMenuItem>
                              <DropdownMenuItem onClick={() => handleForceSyncCampaign(campaign.id)}>
                                <RefreshCw className="w-4 h-4 mr-2" />
                                Forçar sincronização
                              </DropdownMenuItem>
                            </>
                          )}
                          {campaign.status === "paused" && (
                            <DropdownMenuItem onClick={() => handleResumeCampaign(campaign)}>
                              <Play className="w-4 h-4 mr-2" />
                              Retomar
                            </DropdownMenuItem>
                          )}
                          <DropdownMenuItem 
                            className="text-destructive"
                            onClick={() => {
                              setDeleteCampaignId(campaign.id);
                              setDeleteCampaignName(campaign.name);
                            }}
                          >
                            Excluir
                          </DropdownMenuItem>
                        </DropdownMenuContent>
                      </DropdownMenu>
                    </TableCell>
                  </TableRow>
                );
              })}
            </TableBody>
          </Table>
        )}
      </div>

      {/* Campaign Report Dialog (new detailed view) */}
      <CampaignReportDialog
        campaign={selectedCampaign}
        open={showReportDialog}
        onOpenChange={setShowReportDialog}
        onRecycleSuccess={fetchData}
        onCampaignUpdated={() => {
          if (selectedCampaign) {
            supabase
              .from('campaigns')
              .select('*')
              .eq('id', selectedCampaign.id)
              .single()
              .then(({ data }) => {
                if (data) {
                  const updated = { ...data, status: data.status as Campaign["status"] };
                  setAllCampaigns(prev => prev.map(c => c.id === updated.id ? updated : c));
                  setSelectedCampaign(updated);
                }
              });
          }
        }}
      />

      {/* Legacy Campaign Details Dialog */}
      <CampaignDetailsDialog
        campaign={selectedCampaign}
        open={showDetailsDialog}
        onOpenChange={setShowDetailsDialog}
        onCampaignUpdated={() => {
          // Refresh the campaign in local state
          if (selectedCampaign) {
            setAllCampaigns(prev => prev.map(c => 
              c.id === selectedCampaign.id ? { ...c, sector_id: undefined } : c
            ));
            // Re-fetch to get updated data
            supabase
              .from('campaigns')
              .select('*')
              .eq('id', selectedCampaign.id)
              .single()
              .then(({ data }) => {
                if (data) {
                  const updated = { ...data, status: data.status as Campaign["status"] };
                  setAllCampaigns(prev => prev.map(c => c.id === updated.id ? updated : c));
                  setSelectedCampaign(updated);
                }
              });
          }
        }}
      />

      {/* Recycle Failures Dialog */}
      <RecycleFailuresDialog
        campaign={recyclingCampaign}
        open={showRecycleDialog}
        onOpenChange={setShowRecycleDialog}
        onSuccess={fetchData}
      />

      {/* Delete Confirmation Dialog */}
      <AlertDialog open={!!deleteCampaignId} onOpenChange={(open) => { if (!open) setDeleteCampaignId(null); }}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Excluir Campanha</AlertDialogTitle>
            <AlertDialogDescription>
              Tem certeza que deseja excluir a campanha <strong>{deleteCampaignName}</strong>?
              <br />
              <span className="text-destructive">
                Esta ação não pode ser desfeita. Todos os dados de envio serão perdidos.
              </span>
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancelar</AlertDialogCancel>
            <AlertDialogAction
              onClick={confirmDeleteCampaign}
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
            >
              Excluir
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </MainLayout>
  );
};

export default Disparos;
