import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface Lead {
  id: string;
  name: string;
  phone: string;
  email: string | null;
  document: string | null;
  city: string | null;
  state: string | null;
  status: string;
  notes: string | null;
  tags: string[] | null;
  custom_fields: Record<string, unknown> | null;
  organization_id: string;
  user_id: string;
  created_at: string;
  updated_at: string;
}

serve(async (req: Request) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabase = createClient(
      Deno.env.get('SUPABASE_URL')!,
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
    );

    // Get auth header
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) {
      return new Response(JSON.stringify({ error: 'Não autorizado' }), {
        status: 401,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }

    // Verify user
    const { data: { user }, error: userError } = await supabase.auth.getUser(
      authHeader.replace('Bearer ', '')
    );

    if (userError || !user) {
      return new Response(JSON.stringify({ error: 'Não autorizado' }), {
        status: 401,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }

    // Get user's organization
    const { data: profile } = await supabase
      .from('profiles')
      .select('organization_id')
      .eq('user_id', user.id)
      .single();

    if (!profile?.organization_id) {
      return new Response(JSON.stringify({ error: 'Organização não encontrada' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }

    const { dryRun = true } = await req.json().catch(() => ({ dryRun: true }));
    console.log(`Running cleanup for organization ${profile.organization_id}, dryRun: ${dryRun}`);

    // Get all leads for the organization
    const { data: allLeads, error: leadsError } = await supabase
      .from('leads')
      .select('*')
      .eq('organization_id', profile.organization_id);

    if (leadsError) {
      throw new Error(`Error fetching leads: ${leadsError.message}`);
    }

    console.log(`Found ${allLeads?.length || 0} total leads`);

    // Group leads by their normalized phone suffix (last 8 digits)
    const leadsByPhoneSuffix = new Map<string, Lead[]>();
    
    for (const lead of allLeads || []) {
      const normalizedPhone = lead.phone.replace(/\D/g, '');
      const phoneSuffix = normalizedPhone.slice(-8);
      
      if (phoneSuffix.length !== 8) continue;
      
      const existing = leadsByPhoneSuffix.get(phoneSuffix) || [];
      existing.push(lead as Lead);
      leadsByPhoneSuffix.set(phoneSuffix, existing);
    }

    // Find duplicates
    const duplicateGroups: Lead[][] = [];
    for (const [suffix, leads] of leadsByPhoneSuffix) {
      if (leads.length > 1) {
        duplicateGroups.push(leads);
      }
    }

    console.log(`Found ${duplicateGroups.length} groups of duplicate leads`);

    const mergeResults: Array<{
      keptLeadId: string;
      keptLeadName: string;
      keptLeadPhone: string;
      deletedLeadIds: string[];
      mergedTags: string[];
    }> = [];

    for (const group of duplicateGroups) {
      // Score each lead to find the best one to keep
      const scored = group.map(lead => {
        let score = 0;
        const isAutoGenerated = lead.name?.startsWith('LeadWhats-') || lead.name?.startsWith('WhatsApp ');
        
        // Has tags = highest priority
        if (lead.tags && lead.tags.length > 0) score += 1000 * lead.tags.length;
        // Has real name (not auto-generated)
        if (lead.name && !isAutoGenerated) score += 500;
        // Has email
        if (lead.email) score += 50;
        // Has document
        if (lead.document) score += 50;
        // Has city/state
        if (lead.city) score += 25;
        if (lead.state) score += 25;
        // Has notes
        if (lead.notes && !lead.notes.includes('criado automaticamente')) score += 30;
        // Has custom fields
        if (lead.custom_fields && Object.keys(lead.custom_fields).length > 0) score += 20;
        // Older lead (has more history potentially)
        score += new Date(lead.created_at).getTime() / 1000000000000;
        
        return { lead, score };
      });

      // Sort by score descending
      scored.sort((a, b) => b.score - a.score);
      
      const leadToKeep = scored[0].lead;
      const leadsToDelete = scored.slice(1).map(s => s.lead);

      // Merge data from deleted leads into kept lead
      const mergedTags = new Set(leadToKeep.tags || []);
      let mergedNotes = leadToKeep.notes || '';
      const mergedCustomFields = { ...(leadToKeep.custom_fields || {}) };
      
      for (const lead of leadsToDelete) {
        // Merge tags
        if (lead.tags) {
          lead.tags.forEach(tag => mergedTags.add(tag));
        }
        // Merge custom fields (don't overwrite existing)
        if (lead.custom_fields) {
          for (const [key, value] of Object.entries(lead.custom_fields)) {
            if (!mergedCustomFields[key]) {
              mergedCustomFields[key] = value;
            }
          }
        }
        // Merge notes
        if (lead.notes && !lead.notes.includes('criado automaticamente') && !mergedNotes.includes(lead.notes)) {
          if (mergedNotes) {
            mergedNotes += '\n---\n' + lead.notes;
          } else {
            mergedNotes = lead.notes;
          }
        }
        // Fill in missing data
        if (!leadToKeep.email && lead.email) leadToKeep.email = lead.email;
        if (!leadToKeep.document && lead.document) leadToKeep.document = lead.document;
        if (!leadToKeep.city && lead.city) leadToKeep.city = lead.city;
        if (!leadToKeep.state && lead.state) leadToKeep.state = lead.state;
      }

      const deletedIds = leadsToDelete.map(l => l.id);

      console.log(`Group: ${group.map(l => `${l.name} (${l.phone})`).join(', ')}`);
      console.log(`  Keeping: ${leadToKeep.name} (${leadToKeep.phone}) with ${Array.from(mergedTags).length} tags`);
      console.log(`  Deleting: ${deletedIds.length} duplicates`);

      if (!dryRun) {
        // Update the lead to keep with merged data
        const { error: updateError } = await supabase
          .from('leads')
          .update({
            tags: Array.from(mergedTags),
            notes: mergedNotes || null,
            custom_fields: Object.keys(mergedCustomFields).length > 0 ? mergedCustomFields : null,
            email: leadToKeep.email,
            document: leadToKeep.document,
            city: leadToKeep.city,
            state: leadToKeep.state,
            updated_at: new Date().toISOString()
          })
          .eq('id', leadToKeep.id);

        if (updateError) {
          console.error(`Error updating lead ${leadToKeep.id}:`, updateError);
          continue;
        }

        // Delete duplicate leads
        const { error: deleteError } = await supabase
          .from('leads')
          .delete()
          .in('id', deletedIds);

        if (deleteError) {
          console.error(`Error deleting leads:`, deleteError);
          continue;
        }

        console.log(`  Successfully merged and deleted ${deletedIds.length} duplicates`);
      }

      mergeResults.push({
        keptLeadId: leadToKeep.id,
        keptLeadName: leadToKeep.name,
        keptLeadPhone: leadToKeep.phone,
        deletedLeadIds: deletedIds,
        mergedTags: Array.from(mergedTags)
      });
    }

    const summary = {
      success: true,
      dryRun,
      totalLeads: allLeads?.length || 0,
      duplicateGroupsFound: duplicateGroups.length,
      leadsToMerge: mergeResults.length,
      totalLeadsToDelete: mergeResults.reduce((acc, r) => acc + r.deletedLeadIds.length, 0),
      results: mergeResults
    };

    console.log('Cleanup summary:', JSON.stringify(summary, null, 2));

    return new Response(JSON.stringify(summary), {
      status: 200,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });

  } catch (error: unknown) {
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    console.error('Cleanup error:', error);
    return new Response(JSON.stringify({ 
      success: false, 
      error: errorMessage 
    }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });
  }
});
