// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vytjufibiwhtvsnvvqri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5dGp1ZmliaXdodHZzbnZ2cXJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ4MzI2MzYsImV4cCI6MjA5MDQwODYzNn0.5rgCe8wEG-Ebi5h0bEL00fOIyVzBH0_LsaxBFtwmqNI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});